---
title: "Code"
author: "Edna Chiang"
date: "July 17, 2018"
output: html_document
---
### Load Libraries
```{r}
library(ape)
library(dplyr)
library(ggplot2)
library(gplots)
library(phangorn)
library(tidyr)
library(vegan)
library(phyloseq)
library(grid)
library(pgirmess)
library(lme4)
#library(miLineage)
#library(pheatmap)
library(RColorBrewer)
library(extrafont)
#library(cowplot)
loadfonts(device="win")
windowsFonts(Times="Arial")
theme_set(theme_bw())
#theme_set(theme_cowplot(font_family = "Arial"))
set.seed(1)
```

### Load Functions
```{r}
g_legend <- function(a.gplot){
   tmp <- ggplot_gtable(ggplot_build(a.gplot))
   leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
   legend <- tmp$grobs[[leg]]
   return(legend)}



veganCovEllipse <- function(cov, center = c(0, 0), scale = 1, npoints = 100) {
    theta <- (0:npoints) * 2 * pi/npoints
    Circle <- cbind(cos(theta), sin(theta))
    t(center + scale * t(Circle %*% chol(cov)))
}



simper.pretty = function(x, metrics, interesting, perc_cutoff, low_cutoff, low_val, output_name){
  library(vegan)
  #handling otu tables for taxa levels
  save=list(0)
  if(grepl("Otu", colnames(x)[1])!=TRUE){
    #converts output from A.Neumann Taxonomy script
    save=list(58)
    x=as.data.frame(t(x))
    orig_names=colnames(x)
    new_names=list()
    l=1
    for(n in colnames(x)){
      ifelse((l<10), (colnames(x)[l]=c(paste0('Otu000',c(l)))), (colnames(x)[l]=c(paste0('Otu00',c(l))))) 
      new_names=append(new_names, colnames(x)[l])
      l=l+1
    }
    orig_names=as.data.frame(orig_names, row.names = as.character(new_names))
  }
  #running simper
  for(variables in interesting){
    test_1=with(metrics, simper(x, metrics[[variables]]))
    #parsing through simper output, saving desired info to table
    for(name in names(test_1)){
      testmx=matrix(ncol=length(interesting))
      testmx=cbind(test_1[[name]]$ord,test_1[[name]]$cusum)
      sorted=testmx[order(testmx[,1]),]
      sorted=cbind(sorted,test_1[[name]]$species)
      sorted=sorted[order(sorted[,2]),]
      t=matrix(sorted[sorted[,2]<=perc_cutoff,],ncol=3)
      i=nrow(t)
      #converting percents to percent of whole
      while(i>1){
        t[i,2]=as.character(as.numeric(t[i,2])-as.numeric(t[i-1,2]))
        i=i-1
      }
      t[,1]=name
      write.table(t,file=paste(output_name,'_simper.csv',sep=""), append=TRUE, sep=",", col.names = FALSE)
    }}
  y=read.table(paste(output_name,'_simper.csv',sep=""), header=FALSE,sep=",",fill = TRUE,row.names = NULL)
  file.remove(paste(output_name,'_simper.csv',sep = ""))
  y=y[-c(1)]
  colnames(y) = c("Comparison", "SIMPER", "OTU")
  #removing results lower than low cutoff
  if(low_cutoff=='y'){
    y=y[!(as.numeric(as.character(y$SIMPER))<low_val),]
  }
  #prevents changing of colnames if OTU table
  if(58 %in% save){
    y$OTU=orig_names[match(y$OTU, rownames(orig_names)),1]
  }
  write.csv(y,file=paste(output_name,'_clean_simper.csv', sep=''))
}



kruskal.pretty = function(otu, metrics, csv, interesting, output_name, taxonomy){
  library(vegan)
  library(dplyr)
  if(grepl("Otu", colnames(otu)[1])!=TRUE){
    #converts output from A.Neuman Taxonomy script
    otu=as.data.frame(t(otu))
  }
  #changing csv$X to rownames to allow proper splitting of comparisons
  csv$X=as.integer(rownames(csv))
  L=list()
  R=list()
  mean_L=c()
  sd_L=c()
  mean_R=c()
  sd_R=c()
  L_mean=c()
  R_mean=c()
  L_sd=c()
  R_sd=c()
  krusk=c()
  tax=c()
  L_abund=c()
  R_abund=c()
  L_abund_sd=c()
  R_abund_sd=c()
  abund=as.matrix(otu)
  abund=abund/rowSums(abund)
  for(b in levels(csv$Comparison)){
    otu_list=dplyr::filter(csv, Comparison==b) #saves otu list for current comparison
    for(i in csv$X){
      if(as.character(csv$Comparison[i])==b){  ##splitting comparisons so can call individually for table generation
        splt=as.data.frame(matrix(unlist(strsplit(as.character(csv$Comparison[i]),'_')), nrow=1, byrow=T))
        cola=as.character(splt[1,1])
        colb=as.character(splt[1,2])
        break
      }
    }
    #saving topic containing var of interest (cola/colb) (less memory intensive)
    for(topic in interesting){
      #preventing crash if there is only one topic in interesting
      if(is.null(levels(metrics[[topic]]))==TRUE){
        topic1=topic
        break
      }
      for(sbtpic in levels(metrics[[topic]])){
        if(sbtpic==cola){
          topic1=topic
          break
        }
      } 
    }
    #iterate thru rows in tpics of intrst til matches cola and colb, generates otu and metrics tbl  ##!Processing can be reduced!##
    for(rowe1 in metrics[[topic1]]){
      for(rowe2 in metrics[[topic1]]){ 
        if(rowe1==cola & rowe2==colb){ 
          listbact=otu[c(metrics[[topic1]]==cola|metrics[[topic1]]==colb),]
          listmet=metrics[c(metrics[[topic1]]==cola|metrics[[topic1]]==colb),]
          break
        }
      }
    }
    #collecting differential abundances
    sample_L=row.names(subset(metrics, metrics[[topic1]] == c(cola)))
    sample_R=row.names(subset(metrics, metrics[[topic1]] == c(colb)))
    #collecting abund values, perform/save mean and stdev calculations
    for(otus in otu_list$OTU){
      for(sample in sample_L){
        L=append(L,abund[sample,otus])
        mean_L[[otus]]=mean(as.numeric(L))
        sd_L[[otus]]=sd(as.numeric(L))
      }
      for(sample in sample_R){
        R=append(R,abund[sample,otus])
        mean_R[[otus]]=mean(as.numeric(R))
        sd_R[[otus]]=sd(as.numeric(R))
      }
      L=list()
      R=list()
    }
    #runs kruskal.test for each otu in simper csv, stores as list, also stores abundances
    for(otus in otu_list$OTU){
      result=kruskal.test(listbact[[otus]]~listmet[[topic1]])
      krusk=append(krusk, result$p.value)
      #stores taxonomic classification for each otu as list
      if(missing(taxonomy)){
        tax=append(tax, c("NA"))
      } else {
        tax=append(tax, as.character(taxonomy[otus, "Taxonomy"]))
      }
      L_mean=append(L_mean, as.character(mean_L[[otus]]))
      R_mean=append(R_mean, as.character(mean_R[[otus]]))
      L_sd=append(L_sd, as.character(sd_L[[otus]]))
      R_sd=append(R_sd, as.character(sd_R[[otus]]))
      
    }
  }
  #adjusted p-values for multiple comparisons
  fdr=p.adjust(krusk, method='fdr')
  #order csv to match 'krusk'/'fdr' list, add p.val, add taxonomy, re-ord to match orig csv, write to csv
  o_csv=dplyr::arrange(csv, Comparison)
  o_csv[,5]=krusk
  o_csv[,6]=fdr
  o_csv[,7]=tax
  o_csv[,8]=L_mean
  o_csv[,9]=L_sd
  o_csv[,10]=R_mean
  o_csv[,11]=R_sd
  o_csv=dplyr::arrange(o_csv, X)
  colnames(o_csv)[which(names(o_csv) == "V5")] <- "krusk_p.val" #changes column header
  colnames(o_csv)[which(names(o_csv) == "V6")] <- "fdr_krusk_p.val"
  colnames(o_csv)[which(names(o_csv) == "V7")] <- "Taxonomy"
  colnames(o_csv)[which(names(o_csv) == "V8")] <- "Left mean abund"
  colnames(o_csv)[which(names(o_csv) == "V9")] <- "Left stdev"
  colnames(o_csv)[which(names(o_csv) == "V10")] <- "Right mean abund"
  colnames(o_csv)[which(names(o_csv) == "V11")] <- "Right stdev"
  o_csv[,1]=NULL
  write.csv(o_csv, file=paste(output_name,"_krusk_simper.csv", sep=""))
}


# https://slowkow.com/notes/heatmap-tutorial/
draw_colnames_45 <- function (coln, gaps, ...) {
    coord <- pheatmap:::find_coordinates(length(coln), gaps)
    x     <- coord$coord - 0.5 * coord$size
    res   <- grid::textGrob(
      coln, x = x, y = unit(1, "npc") - unit(3,"bigpts"),
      vjust = 0.75, hjust = 1, rot = 45, gp = grid::gpar(...)
    )
    return(res)
}
assignInNamespace(
  x = "draw_colnames",
  value = "draw_colnames_45",
  ns = asNamespace("pheatmap")
)
```

### Import Data
```{r}
# Link files
shared = "mothur_outputs/final.shared"
taxonomy = "mothur_outputs/final.taxonomy"


# Import mothur data
mothurdata = import_mothur(
  mothur_shared_file = shared,
  mothur_constaxonomy_file = taxonomy)

# Add OTU column in taxonomy table
tax_table(mothurdata) <- cbind(tax_table(mothurdata), 
                               row.names(tax_table(mothurdata)))

# Rename taxonomy table columns
colnames(tax_table(mothurdata)) <- 
  c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species")

```

### Explore mothurdata object
```{r}
samp.sum <- data.frame(colSums(otu_table(mothurdata)))
colnames(samp.sum) <- "Sample_TotalSeqs"
samp.sum$sample <- row.names(samp.sum)
samp.sum <- arrange(samp.sum, Sample_TotalSeqs)

ggplot(samp.sum, aes(x=reorder(sample, Sample_TotalSeqs), y=Sample_TotalSeqs)) +
  ylab("Number of Sequences per Sample") +
  geom_bar(stat="identity", colour="black", fill="cornflowerblue") +
  xlab("Sample Name") +
  ggtitle("Total Number of Sequences per Sample") + 
  theme(axis.text.x = element_text(colour = "black", size=6, angle=45,hjust = 1,
                                   vjust = 1))

ggplot(data.frame(sum = sample_sums(mothurdata)), aes(sum)) + 
  geom_histogram(colour = "white", fill = "blue", bins=60) + 
  ggtitle("Sample read counts") + 
  xlab("total sequences")


# Min, Mean, Max of sample read counts
min(sample_sums(mothurdata))
mean(sample_sums(mothurdata))
median(sample_sums(mothurdata))
max(sample_sums(mothurdata))
```


### Create Phyloseq Object
```{r}
meta <- read.csv("metadata.csv")
colnames(meta)[1] <- "Sample_ID"
rownames(meta) <- meta$Sample
meta$Time <- ordered(meta$Time, levels=c("Pre-treatment", "Post-treatment"))
meta$Treatment <- ordered(meta$Treatment, levels=c("Low Fat", "High Fat", "Saccharin", "Stevia"))
divsum <- read.table("mothur_outputs/final.summary", header=T)


# Add in diversity summaries
meta[,9:19] <- divsum[,3:12]

# Create intermin phyloseq object
physeq <- merge_phyloseq(mothurdata, sample_data(meta))
#save(physeq, file="Physeq.RData")

# Subset out paired samples
physeq.pair <- subset_samples(physeq, Sample_ID != "HF8C")
physeq.pair <- subset_samples(physeq.pair, Sample_ID != "SC4A")
physeq.pair <- subset_samples(physeq.pair, Sample_ID != "TV2A")
physeq.pair <- subset_samples(physeq.pair, Sample_ID != "TV8A")
#save(physeq.pair, file="Physeq.pair.RData")

# Subset out Pre vs. Post
physeq.pre <- subset_samples(physeq.pair, Time == "Pre-treatment")
#save(physeq.pre, file="Physeq.pre.RData")
physeq.post <- subset_samples(physeq.pair, Time == "Post-treatment")
#save(physeq.post, file="Physeq.post.RData")

# Subset Post w/o Low Fat (due to skewing)
physeq.post.rem <- subset_samples(physeq.post, Treatment != "Low Fat")
#save(physeq.post.rem, file="Physeq.post.rem.RData")

# Subset out Female vs. Male
physeq.fem <- subset_samples(physeq.pair, Sex == "Female")
#save(physeq.fem, file="Physeq.fem.RData")
physeq.mal <- subset_samples(physeq.pair, Sex == "Male")
#save(physeq.mal, file="Physeq.mal.RData")

# Subset out Sex + Time
physeq.pre.fem <- subset_samples(physeq.pre, Sex == "Female")
#save(physeq.pre.fem, file="Physeq.pre.fem.RData")
physeq.pre.mal <- subset_samples(physeq.pre, Sex == "Male")
#save(physeq.pre.mal, file="Physeq.pre.mal.RData")
physeq.post.fem <- subset_samples(physeq.post, Sex == "Female")
#save(physeq.post.fem, file="Physeq.post.fem.RData")
physeq.post.mal <- subset_samples(physeq.post, Sex == "Male")
#save(physeq.post.mal, file="Physeq.post.mal.RData")

# Remove Low Fat from Sex + Post subsets
physeq.post.fem.rem <- subset_samples(physeq.post.fem, Treatment != "Low Fat")
#save(physeq.post.fem.rem, file="Physeq.post.fem.rem.RData")
physeq.post.mal.rem <- subset_samples(physeq.post.mal, Treatment != "Low Fat")
#save(physeq.post.mal.rem, file="Physeq.post.mal.rem.RData")

# Subset out treatments
physeq.hf <- subset_samples(physeq.pair, Treatment == "High Fat")
#save(physeq.hf, file = "Physeq.hf.RData")
physeq.lf <- subset_samples(physeq.pair, Treatment == "Low Fat")
#save(physeq.lf, file = "Physeq.lf.RData")
physeq.sc <- subset_samples(physeq.pair, Treatment == "Saccharin")
#save(physeq.sc, file = "Physeq.sc.RData")
physeq.tv <- subset_samples(physeq.pair, Treatment == "Stevia")
#save(physeq.tv, file = "Physeq.tv.RData")

```

### Load Phyloseq Object
```{r}
load("physeq/Physeq.RData")
load("physeq/Physeq.pair.RData")
load("physeq/Physeq.pre.RData")
load("physeq/Physeq.post.RData")
load("physeq/Physeq.post.rem.RData")
load("physeq/Physeq.fem.RData")
load("physeq/Physeq.mal.RData")
load("physeq/Physeq.pre.fem.RData")
load("physeq/Physeq.pre.mal.RData")
load("physeq/Physeq.post.fem.RData")
load("physeq/Physeq.post.mal.RData")
load("physeq/Physeq.post.fem.rem.RData")
load("physeq/Physeq.post.mal.rem.RData")
load("physeq/Physeq.hf.RData")
load("physeq/Physeq.lf.RData")
load("physeq/Physeq.sc.RData")
load("physeq/Physeq.tv.RData")
```

### Alpha Div
```{r}
adiv <- data.frame(sample_data(physeq))
adiv.pair <- data.frame(sample_data(physeq.pair))

### Coverage
# Plot
ggplot(adiv.pair, aes(x=Treatment, y= coverage, fill = Treatment)) +
  geom_boxplot(position=position_dodge(1)) +
  geom_point() + 
  facet_grid(.~Time) +
  xlab("Treatment") +
  scale_fill_manual(values=c("rosybrown", "brown2", "limegreen", "dodgerblue2")) +
  ylab("Coverage")
# Test normality
hist(adiv.pair$coverage, breaks=10)
qqnorm(adiv.pair$coverage)
qqline(adiv.pair$coverage)
shapiro.test(adiv.pair$coverage)
  # p-value = 0.003709
  # Not normal


### Total OTUs
otu.tot <- data.frame(sample_names(physeq.pair))
# Pull out # of OTUs from all samples
otu.tot$Total_OTUs <- rep("NA", 72)
for(i in 1:72){
  otu.tot[i,2] <- length(which(otu_table(physeq.pair)[,i] != 0))
}
adiv.pair$Total_OTUs <- otu.tot$Total_OTUs
adiv.pair$Total_OTUs <- as.numeric(adiv.pair$Total_OTUs)
adiv.pair.pre <- adiv.pair[which(adiv.pair$Time == "Pre-treatment"),]
adiv.pair.post <- adiv.pair[which(adiv.pair$Time == "Post-treatment"),]
# Plot
ggplot(adiv.pair, aes(x=Treatment, y=Total_OTUs, fill = Treatment)) +
  geom_boxplot(position=position_dodge(1)) +
  geom_point() + 
  facet_grid(.~Time) +
  xlab("Treatment") +
  scale_fill_manual(values=c("rosybrown", "brown2", "limegreen", "dodgerblue2")) +
  ylab("Total OTUs")
# Test normality
hist(adiv.pair$Total_OTUs, breaks=10)
qqnorm(adiv.pair$Total_OTUs)
qqline(adiv.pair$Total_OTUs)
shapiro.test(adiv.pair$Total_OTUs)
  # p-value = 0.002107
  # Not normal
# Stats
kruskal.test(formula = Total_OTUs ~ Treatment, data=adiv.pair[which(adiv.pair$Time == "Pre-treatment"),])
  # All Pre-treatment
  # p-value = 0.003924
kruskalmc(resp = Total_OTUs ~ Treatment, data = adiv.pair[which(adiv.pair$Time == "Pre-treatment"),])
  # Pre-treatment Significant:  
      # Low fat - saccharin
kruskal.test(formula = Total_OTUs ~ Treatment, data=adiv.pair[which(adiv.pair$Time == "Post-treatment"),])
  # All Post-treatment
  # p-value = 0.009035
kruskalmc(resp = Total_OTUs ~ Treatment, data = adiv.pair[which(adiv.pair$Time == "Post-treatment"),])
  # Post-treatment Significant:
    # High Fat - Low Fat
#friedman.test(formula = Total_OTUs ~ Treatment | Time, data = adiv.pair)
wilcox.test(Total_OTUs ~ Time, data=adiv.pair, paired=T)
  # p-value = 0.5245
wilcox.test(Total_OTUs ~ Sex, data = adiv.pair[which(adiv.pair$Time == "Pre-treatment"),])
  # Pre-treatment Sex
  # p-value = 0.6015
wilcox.test(Total_OTUs ~ Sex, data = adiv.pair[which(adiv.pair$Time == "Post-treatment"),])
  # Post-treatment Sex
  # p-value = 0.1589
# Repeated Measure
summary(lmer(Total_OTUs ~ Time + Treatment + Sex + (1|Subj_ID), data=adiv.pair))
  # Variance explained by Subj_ID = 0.0

### Chao
# Plot
#tiff("Chao.tiff", width=6.5, height=3, units="in", res=600)
chao.ann <- data.frame(lab=c("ab", "c", "c", "bc"), Time = factor(c("Post-treatment", "Post-treatment", "Post-treatment", "Post-treatment")), Treatment = factor(c("Low Fat", "High Fat", "Saccharin", "Stevia")))
  # Annotations
chao.plot <- ggplot(adiv.pair, aes(x=Treatment, y=chao, fill = Treatment)) +
  geom_boxplot(position=position_dodge(1)) +
  geom_point(position = position_dodge(width = 0.2)) + 
  facet_grid(.~Time) +
  xlab("Treatment") + 
  scale_fill_manual(values=c("rosybrown", "brown2", "limegreen", "dodgerblue2")) +
  ylab("Chao Richness") +
  scale_y_continuous(breaks = c(50, 100, 150, 200, 250, 300, 350), limits = c(50,350)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(family="Arial", size=10),
        axis.text.y = element_text(family="Arial", size=10),
        axis.title.x = element_text(family="Arial", size=10, face="bold"),
        axis.title.y = element_text(family="Arial", size=10, face="bold"),
        legend.title = element_text(family="Arial", size=10, face="bold"),
        legend.text = element_text(family="Arial", size=10),
        plot.title = element_text(family = "Arial", size=10, face="bold"),
        strip.text.x = element_text(family="Arial", size=10)
        ) +
  geom_text(data = chao.ann, aes(label=lab), x=c(1,2,3,4), y=c(350,350,350,350), 
            size=4, color="black", family="Arial")






#dev.off()
# Test normality
hist(adiv.pair$chao, breaks=10)
qqnorm(adiv.pair$chao)
qqline(adiv.pair$chao)
shapiro.test(adiv.pair$chao)
  # p-value = 5.717e-05
  # Not normal
# Stats
kruskal.test(formula = chao ~ Treatment, data=adiv.pair[which(adiv.pair$Time == "Pre-treatment"),])
  # All Pre-treatment
  # p-value = 0.4731
kruskal.test(formula = chao ~ Treatment, data=adiv.pair[which(adiv.pair$Time == "Post-treatment"),])
  # All Post-treatment
  # p-value = 0.0003939
kruskalmc(resp = chao ~ Treatment, data = adiv.pair[which(adiv.pair$Time == "Post-treatment"),])
  # Post-treatment Significant:
    # High Fat - Low Fat
    # Low Fat - Saccharin
pairwise.wilcox.test(adiv.pair$chao, adiv.pair$Treatment, p.adjust.method = "fdr")
  # LowFat - HighFat = 0.014
  # Saccharin - HighFat = 0.865
  # Saccharin - LowFat = 0.007
  # Stevia - HighFat = 0.986
  # Stevia - LowFat = 0.018
  # Stevia - Saccharin = 0.865
  ## Low fat vs. high fat = sig diff
#friedman.test(formula = chao ~ Treatment | Time, data = adiv.pair)
wilcox.test(chao ~ Time, data=adiv.pair, paired=T)
  # p-value = 0.02096
wilcox.test(chao ~ Time, data=adiv.pair[which(adiv.pair$Treatment == "High Fat"),], paired=T)
  # High Fat
  # p-value = 0.003906
wilcox.test(chao ~ Time, data=adiv.pair[which(adiv.pair$Treatment == "Low Fat"),], paired=T)
  # Low Fat
  # p-value = 0.4316
wilcox.test(chao ~ Time, data=adiv.pair[which(adiv.pair$Treatment == "Saccharin"),], paired=T)
  # Saccharin
  # p-value = 0.07422
wilcox.test(chao ~ Time, data=adiv.pair[which(adiv.pair$Treatment == "Stevia"),], paired=T)
  # Stevia
  # p-value = 0.3125
wilcox.test(chao ~ Sex, data = adiv.pair[which(adiv.pair$Time == "Pre-treatment"),])
  # Pre-treatment Sex
  # p-value = 1
wilcox.test(chao ~ Sex, data = adiv.pair[which(adiv.pair$Time == "Post-treatment"),])
  # Post-treatment Sex
  # p-value = 0.8147
# Repeated Measures
summary(lmer(chao ~ Time + Treatment + Sex + (1|Subj_ID), data=adiv.pair))
  # Variance explained by Subj_ID = 1.376e-13


### Shannon
# Plot
shannon.plot <- ggplot(adiv.pair, aes(x=Treatment, y=shannon, fill = Treatment)) +
  geom_boxplot(position=position_dodge(1)) +
  geom_point(position = position_dodge(width = 0.2)) + 
  facet_grid(.~Time) +
  scale_fill_manual(values=c("rosybrown", "brown2", "limegreen", "dodgerblue2")) +
  xlab("Treatment") +
  ylab("Shannon Diversity") +
  scale_y_continuous(breaks=c(2.75, 3.00, 3.25, 3.50, 3.75), limits= c(2.75, 3.75)) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(family="Arial", size=10),
        axis.text.y = element_text(family="Arial", size=10),
        axis.title.x = element_text(family="Arial", size=10, face="bold"),
        axis.title.y = element_text(family="Arial", size=10, face="bold"),
        legend.title = element_text(family="Arial", size=10, face="bold"),
        legend.text = element_text(family="Arial", size=10),
        plot.title = element_text(family = "Arial", size=10, face="bold"),
        strip.text.x = element_text(family="Arial", size=10)
        )
# Test normality
hist(adiv.pair$shannon, breaks=10)
qqnorm(adiv.pair$shannon)
qqline(adiv.pair$shannon)
shapiro.test(adiv.pair$shannon)
  # p-value = 0.5704
  # Normal
# Stats
summary(aov(shannon ~ Treatment, data = adiv.pair[which(adiv.pair$Time == "Pre-treatment"),]))
  # Pre-treatment
  # P-value = 0.589
summary(aov(shannon ~ Treatment, data = adiv.pair[which(adiv.pair$Time == "Post-treatment"),]))
  # Post-treatment
  # P-value = 0.043
TukeyHSD(aov(shannon ~ Treatment, data = adiv.pair[which(adiv.pair$Time == "Post-treatment"),]))
  # Post-treatment Significance:
    # Saccharin - Low Fat
t.test(shannon ~ Time, data = adiv.pair, paired=T)
  # p-value = 0.9899
t.test(shannon ~ Time, data = adiv.pair[which(adiv.pair$Treatment == "High Fat"),], paired=T)
  # High Fat
  # p-value = 0.9751
t.test(shannon ~ Time, data = adiv.pair[which(adiv.pair$Treatment == "Low Fat"),], paired=T)
  # Low Fat
  # p-value = 0.03614
t.test(shannon ~ Time, data = adiv.pair[which(adiv.pair$Treatment == "Saccharin"),], paired=T)
  # Saccharin
  # p-value = 0.192
t.test(shannon ~ Time, data = adiv.pair[which(adiv.pair$Treatment == "Stevia"),], paired=T)
  # Stevia
  # p-value = 0.1537
t.test(shannon ~ Sex, data = adiv.pair[which(adiv.pair$Time == "Pre-treatment"),])
  # Pre-treatment Sex
  # p-value = 0.6813
t.test(shannon ~ Sex, data = adiv.pair[which(adiv.pair$Time == "Post-treatment"),])
  # Post-treatment Sex
  # p-value = 0.01769
t.test(shannon ~ Time, data = adiv.pair[which(adiv.pair[which(adiv.pair$Treatment == "High Fat"),]$Sex == "Female"),], paired=T)
  # Female High Fat Time
  # p-value = 0.4814
t.test(shannon ~ Time, data = adiv.pair[which(adiv.pair[which(adiv.pair$Treatment == "High Fat"),]$Sex == "Male"),], paired=T)
  # Male High Fat Time
  # p-value = 0.05131
t.test(shannon ~ Time, data = adiv.pair[which(adiv.pair[which(adiv.pair$Treatment == "Low Fat"),]$Sex == "Female"),], paired=T)
  # Female Low Fat Time
  # p-value = 0.11
t.test(shannon ~ Time, data = adiv.pair[which(adiv.pair[which(adiv.pair$Treatment == "Low Fat"),]$Sex == "Male"),], paired=T)
  # Male Low Fat Time
  # p-value = 0.2679
t.test(shannon ~ Time, data = adiv.pair[which(adiv.pair[which(adiv.pair$Treatment == "Saccharin"),]$Sex == "Female"),], paired=T)
  # Female Saccharin Time
  # p-value = 0.1392
t.test(shannon ~ Time, data = adiv.pair[which(adiv.pair[which(adiv.pair$Treatment == "Saccharin"),]$Sex == "Male"),], paired=T)
  # Male Saccharin Time
  # p-value = 0.2168
t.test(shannon ~ Time, data = adiv.pair[which(adiv.pair[which(adiv.pair$Treatment == "Stevia"),]$Sex == "Female"),], paired=T)
  # Female Stevia Time
  # p-value = 0.5392
t.test(shannon ~ Time, data = adiv.pair[which(adiv.pair[which(adiv.pair$Treatment == "Stevia"),]$Sex == "Male"),], paired=T)
  # Male Stevia Time
  # p-value = 0.05621
# Repeated Measure
summary(lmer(shannon ~ Time + Treatment + Sex + (1|Subj_ID), data=adiv.pair))
  # Variance explained by Subj_ID = 0

```


### Alpha Div Plot
```{r}
tiff("adiv.tiff", width=180, height = 125, units="mm", res = 600)
grid.newpage()
pushViewport(viewport(layout=(grid.layout(4,1, widths=c(1,1,1,1), heights=c(0.055,1,0.055,1)))))
grid.text("A", x=unit(0.03, "npc"), vp=viewport(layout.pos.row=1, layout.pos.col=1),
          gp=gpar(fontsize=12,fontface="bold",fontfamily="Arial"))
print(chao.plot, vp=viewport(layout.pos.row=2, layout.pos.col=1))
grid.text("B", x=unit(0.03, "npc"), vp=viewport(layout.pos.row=3, layout.pos.col=1),
          gp=gpar(fontsize=12,fontface="bold",fontfamily="Arial"))
print(shannon.plot, vp=viewport(layout.pos.row=4, layout.pos.col=1))
dev.off()
```
### Examine Phyla
```{r}
# Merge samples with the same taxonomic rank
goodphy <- tax_glom(physeq.pair, taxrank="Phylum")

# Transform each merged phylum count to rel abund
phy99 <- transform_sample_counts(goodphy, function(x){(x/sum(x))*100})

# Remove any phyla with <0.1% rel abund
phy99 <- prune_taxa(taxa_sums(phy99) > 0.1, phy99)

# Create rank abundance of phyla
barplot(sort(taxa_sums(phy99),TRUE)[1:20]/nsamples(phy99),las=2,cex.axis=.7)


# Summarize data
phy.df <- psmelt(phy99)
phy.df$Phylum <- ordered(phy.df$Phylum, levels=c("Firmicutes", "Bacteroidetes", "Verrucomicrobia", "Tenericutes", "Proteobacteria", "Actinobacteria", "Unclassified", "Cyanobacteria"))
phy.df$Phylum[which(is.na(phy.df$Phylum))] <- rep("Unclassified",length(which(is.na(phy.df$Phylum))))
phy.sum <- phy.df %>%
  group_by(Treatment, Time, Phylum) %>%
  summarize(Mean = mean(Abundance),
            Median = median(Abundance),
            SD = sd(Abundance),
            SE = (sd(Abundance)/(sqrt(length(Abundance)))),
            iqr = IQR(Abundance))
phy.all.sum <- phy.df %>%
  group_by(Phylum) %>%
  summarize(Mean = mean(Abundance),
            Median = median(Abundance),
            SD = sd(Abundance),
            SE = (sd(Abundance)/(sqrt(length(Abundance)))),
            iqr = IQR(Abundance))

# Calculate IQR limits
phy.sum$iqr.min <- phy.sum$Median - 0.5*phy.sum$iqr
phy.sum[which(phy.sum$iqr.min < 0),10] <- 0
  # Any IQR min < 0, change to 0 (otherwise error bar won't plot)
phy.sum$iqr.max <- phy.sum$Median + 0.5*phy.sum$iqr


### Barplot ###
tiff("phyla.tiff", width = 180, height = 100, units = "mm", res = 600)
ggplot(phy.sum, aes(x=Phylum, y=Median, fill=Phylum)) +
  geom_bar(stat="identity", color="black") +
  facet_grid(Time ~ Treatment) +
  geom_errorbar(aes(ymax=iqr.max, ymin=iqr.min), width=0.25) +
  scale_fill_manual(values=c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#f781bf", "#a65628", "#ffff33", "#ff7f00")) +
  xlab("Phyla") +
  ylab("Median Relative Abundance for Phyla > 0.1%") +
  scale_y_continuous(limits=c(0,80), expand=c(0,0))+
  theme(panel.grid.major = element_blank(),
        #panel.grid.minor = element_blank(),
        axis.text.x = element_blank(),
        panel.spacing=unit(1, "lines"),
        axis.title = element_text(size=12, family="Arial", face="bold"),
        strip.text.x = element_text(size=12, family="Arial"),
        strip.text.y = element_text(size=12, family="Arial"),
        axis.text.y = element_text(size=12, family="Arial"),
        legend.title = element_text(size=12, family="Arial", face="bold"),
        legend.text = element_text(size=12, family="Arial"),
        axis.ticks.x=element_blank())
dev.off()


### Testing barplot for sex + treatment + time
test <- phy.df %>%
  group_by(Treatment, Time, Sex, Phylum) %>%
  summarize(Mean = mean(Abundance),
            Median = median(Abundance),
            SD = sd(Abundance),
            SE = (sd(Abundance)/(sqrt(length(Abundance)))),
            iqr = IQR(Abundance))
test$iqr.min <- test$Median - 0.5*test$iqr
test[which(test$iqr.min < 0),10] <- 0
  # Any IQR min < 0, change to 0 (otherwise error bar won't plot)
test$iqr.max <- test$Median + 0.5*test$iqr
ggplot(test, aes(x=Phylum, y=Median, fill=Phylum)) +
  geom_bar(stat="identity", color="black") +
  facet_grid(Time + Sex ~ Treatment) +
  geom_errorbar(aes(ymax=iqr.max, ymin=iqr.min), width=0.25) +
  scale_fill_manual(values=c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#f781bf", "#a65628", "#ffff33", "#ff7f00")) +
  xlab("Phyla") +
  ylab("Median Relative Abundance for Phyla > 0.01%") +
  scale_y_continuous(limits=c(0,80), expand=c(0,0))+
  theme(axis.text.x = element_blank(),
        panel.spacing=unit(1, "lines"),
        axis.title = element_text(size=20),
        strip.text.x = element_text(size=14),
        strip.text.y = element_text(size=14),
        axis.text.y = element_text(size=12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size=12))
test <- phy.df %>%
  group_by(Time, Sex, Phylum) %>%
  summarize(Mean = mean(Abundance),
            Median = median(Abundance),
            SD = sd(Abundance),
            SE = (sd(Abundance)/(sqrt(length(Abundance)))),
            iqr = IQR(Abundance))
test$iqr.min <- test$Median - 0.5*test$iqr
test[which(test$iqr.min < 0),10] <- 0
  # Any IQR min < 0, change to 0 (otherwise error bar won't plot)
test$iqr.max <- test$Median + 0.5*test$iqr
ggplot(test, aes(x=Phylum, y=Median, fill=Phylum)) +
  geom_bar(stat="identity", color="black") +
  facet_grid(Time~ Sex) +
  geom_errorbar(aes(ymax=iqr.max, ymin=iqr.min), width=0.25) +
  scale_fill_manual(values=c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#f781bf", "#a65628", "#ffff33", "#ff7f00")) +
  xlab("Phyla") +
  ylab("Median Relative Abundance for Phyla > 0.01%") +
  scale_y_continuous(limits=c(0,80), expand=c(0,0))+
  theme(axis.text.x = element_blank(),
        panel.spacing=unit(1, "lines"),
        axis.title = element_text(size=20),
        strip.text.x = element_text(size=14),
        strip.text.y = element_text(size=14),
        axis.text.y = element_text(size=12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size=12))
```


### Test Phyla
```{r}
### Code to answer Sarah's questions

### Firmicutes in Stevia, Pre vs. Post
fir.phy <- subset_taxa(phy99, Phylum == "Firmicutes")
fir.tv <- subset_samples(fir.phy, Treatment == "Stevia")
fir.tv.df <- data.frame(sample_data(fir.tv))
fir.tv.df$RelAbund <- t(data.frame(otu_table(fir.tv)))
# Wilcoxon (Paired)
wilcox.test(RelAbund ~ Time, data=fir.tv.df, paired=T, alternative = "less")
  # p-value = 0.01172
  # Pre < Post

### Firmicutes in all Post High Fat diets vs. Low Fat
fir.phy <- subset_taxa(phy99, Phylum == "Firmicutes")
fir.post <- subset_samples(fir.phy, Time == "Post-treatment")
fir.post.df <- data.frame(sample_data(fir.post))
fir.post.df$RelAbund <- t(data.frame(otu_table(fir.post)))
fir.post.df$Diet <- NA
fir.post.df$Diet[which(fir.post.df$Treatment == "Low Fat")] <- "Low Fat"
fir.post.df$Diet[which(fir.post.df$Treatment != "Low Fat")] <- "High Fat"
# Wilcoxon
wilcox.test(RelAbund ~ Diet, data=fir.post.df, alternative = "greater")
  # p-value = 3.05e-05
  # High Fat > Low Fat


### Bacteroidetes in all Post High Fat diets vs. Low Fat
bac.phy <- subset_taxa(phy99, Phylum == "Bacteroidetes")
bac.post <- subset_samples(bac.phy, Time == "Post-treatment")
bac.post.df <- data.frame(sample_data(bac.post))
bac.post.df$RelAbund <- t(data.frame(otu_table(bac.post)))
bac.post.df$Diet <- NA
bac.post.df$Diet[which(bac.post.df$Treatment == "Low Fat")] <- "Low Fat"
bac.post.df$Diet[which(bac.post.df$Treatment != "Low Fat")] <- "High Fat"
# Wilcoxon
wilcox.test(RelAbund ~ Diet, data=bac.post.df, alternative = "less")
  # p-value = .3.934e-09
  # High Fat < Low Fat

```

### Examine Family
```{r}
# Merge samples with the same taxonomic rank
goodfam <- tax_glom(physeq.pair, taxrank="Family")

# Transform each merged phylum count to rel abund
fam99 <- transform_sample_counts(goodfam, function(x){(x/sum(x))*100})

# Remove any phyla with <1% rel abund
fam99 <- prune_taxa(taxa_sums(fam99) > 0.1, fam99)

# Create rank abundance of phyla
barplot(sort(taxa_sums(fam99),TRUE)[1:20]/nsamples(fam99),las=2,cex.axis=.7)

# Take top 10 families for plotting
fam.top10 <- sort(taxa_sums(fam99), TRUE)[1:10]
fam.top10 <- prune_taxa(taxa_sums(fam99) > 68, fam99)

# Summarize data
fam.df <- psmelt(fam.top10)
fam.df$Phylum <- ordered(fam.df$Family, levels=c("S24-7", "Lachnospiraceae", "Ruminococcaceae", "Verrucomicrobiaceae", "Bacteroidaceae", "vadinBB60", "Anaeroplasmataceae", "Rikenellaceae", "Streptocccaaceae", "Erysipelotrichaceae"))
fam.df$Family[which(is.na(fam.df$Family))] <- rep("Unclassified",length(which(is.na(fam.df$Family))))
fam.sum <- fam.df %>%
  group_by(Treatment, Time, Family) %>%
  summarize(Mean = mean(Abundance),
            Median = median(Abundance),
            SD = sd(Abundance),
            SE = (sd(Abundance)/(sqrt(length(Abundance)))),
            iqr = IQR(Abundance))

# Calculate IQR limits
fam.sum$iqr.min <- fam.sum$Median - 0.5*fam.sum$iqr
fam.sum[which(fam.sum$iqr.min < 0),10] <- 0
  # Any IQR min < 0, change to 0 (otherwise error bar won't plot)
fam.sum$iqr.max <- fam.sum$Median + 0.5*fam.sum$iqr


### Barplot ###
#tiff("familyfacet.tiff", width = 13, height = 8, units = "in", res = 300)
ggplot(fam.sum, aes(x=Family, y=Median, fill=Family)) +
  geom_bar(stat="identity", color="black") +
  facet_grid(Time ~ Treatment) +
  geom_errorbar(aes(ymax=iqr.max, ymin=iqr.min), width=0.25) +
  scale_fill_manual(values=c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#f781bf", "#a65628", "#ffff33", "#ff7f00", "dimgray", "darkgray")) +
  xlab("Phyla") +
  ylab("Median Relative Abundance for Family > 0.1%") +
  scale_y_continuous(limits=c(0,80), expand=c(0,0))+
  theme(axis.text.x = element_blank(),
        panel.spacing=unit(1, "lines"),
        axis.title = element_text(size=20),
        strip.text.x = element_text(size=14),
        strip.text.y = element_text(size=14),
        axis.text.y = element_text(size=12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size=12))
#dev.off()


### Testing barplot for sex + treatment + time
test <- phy.df %>%
  group_by(Treatment, Time, Sex, Phylum) %>%
  summarize(Mean = mean(Abundance),
            Median = median(Abundance),
            SD = sd(Abundance),
            SE = (sd(Abundance)/(sqrt(length(Abundance)))),
            iqr = IQR(Abundance))
test$iqr.min <- test$Median - 0.5*test$iqr
test[which(test$iqr.min < 0),10] <- 0
  # Any IQR min < 0, change to 0 (otherwise error bar won't plot)
test$iqr.max <- test$Median + 0.5*test$iqr
ggplot(test, aes(x=Phylum, y=Median, fill=Phylum)) +
  geom_bar(stat="identity", color="black") +
  facet_grid(Time + Sex ~ Treatment) +
  geom_errorbar(aes(ymax=iqr.max, ymin=iqr.min), width=0.25) +
  scale_fill_manual(values=c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#f781bf", "#a65628", "#ffff33", "#ff7f00")) +
  xlab("Phyla") +
  ylab("Median Relative Abundance for Phyla > 0.01%") +
  scale_y_continuous(limits=c(0,80), expand=c(0,0))+
  theme(axis.text.x = element_blank(),
        panel.spacing=unit(1, "lines"),
        axis.title = element_text(size=20),
        strip.text.x = element_text(size=14),
        strip.text.y = element_text(size=14),
        axis.text.y = element_text(size=12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size=12))
test <- phy.df %>%
  group_by(Time, Sex, Phylum) %>%
  summarize(Mean = mean(Abundance),
            Median = median(Abundance),
            SD = sd(Abundance),
            SE = (sd(Abundance)/(sqrt(length(Abundance)))),
            iqr = IQR(Abundance))
test$iqr.min <- test$Median - 0.5*test$iqr
test[which(test$iqr.min < 0),10] <- 0
  # Any IQR min < 0, change to 0 (otherwise error bar won't plot)
test$iqr.max <- test$Median + 0.5*test$iqr
ggplot(test, aes(x=Phylum, y=Median, fill=Phylum)) +
  geom_bar(stat="identity", color="black") +
  facet_grid(Time~ Sex) +
  geom_errorbar(aes(ymax=iqr.max, ymin=iqr.min), width=0.25) +
  scale_fill_manual(values=c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#f781bf", "#a65628", "#ffff33", "#ff7f00")) +
  xlab("Phyla") +
  ylab("Median Relative Abundance for Phyla > 0.01%") +
  scale_y_continuous(limits=c(0,80), expand=c(0,0))+
  theme(axis.text.x = element_blank(),
        panel.spacing=unit(1, "lines"),
        axis.title = element_text(size=20),
        strip.text.x = element_text(size=14),
        strip.text.y = element_text(size=14),
        axis.text.y = element_text(size=12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size=12))
```






### Bray-Curtis NMDS
```{r}
### Paired
bray.nmds <- ordinate(physeq=physeq.pair, method="NMDS", distance="bray")
  # stress = 7.705923e-05 

all.nmds <- plot_ordination(physeq=physeq.pair, ordination=bray.nmds, color="Treatment", shape="Time") +
  scale_shape_manual(values=c(19,2)) +
  scale_color_manual(values=c("rosybrown", "brown2", "limegreen", "dodgerblue2")) +
  ggtitle("All Samples") +
  #geom_point(size=2, stroke=1.5) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(family="Arial", size=8),
        axis.text.y = element_text(family="Arial", size=8),
        axis.title.x = element_text(family="Arial", size=8, face="bold"),
        axis.title.y = element_text(family="Arial", size=8, face="bold"),
        legend.title = element_text(family="Arial", size=10, face="bold"),
        legend.text = element_text(family="Arial", size=10),
        plot.title = element_text(family = "Arial", size=10, face="bold", hjust=0.5)
        ) +
  annotate("text", x = 0.61, y = -1.12e-04, label = "stress = 0.00007", size=3, family="Arial")
 

### Pre-treatment
bray.nmds.pre <- ordinate(physeq=physeq.pre, method="NMDS", distance="bray")
  # stress = 0.1929748 
pre.nmds <- plot_ordination(physeq=physeq.pre, ordination=bray.nmds.pre, color="Treatment", shape="Sex") +
  scale_shape_manual(values=c(19,2)) +
  scale_color_manual(values=c("rosybrown", "brown2", "limegreen", "dodgerblue2")) +
  ggtitle("Pre-treatment") +
  #geom_point(size=2, stroke=1.5) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(family="Arial", size=8),
        axis.text.y = element_text(family="Arial", size=8),
        axis.title.x = element_text(family="Arial", size=8, face="bold"),
        axis.title.y = element_text(family="Arial", size=8, face="bold"),
        legend.title = element_text(family="Arial", size=10, face="bold"),
        legend.text = element_text(family="Arial", size=10),
        plot.title = element_text(family = "Arial", size=10, face="bold", hjust=0.5)
        ) +
  annotate("text", x = 0.29, y = -0.52, label = "stress = 0.193", size=2, family="Arial") +
  guides(colour=FALSE, shape=FALSE)
# Steal legend
nmds.legend <- g_legend(pre.nmds)


# Treatment Ellipses
sample_data(physeq.pre)$Elip.treat <- paste(sample_data(physeq.pre)$Treatment)
elip.nmds.pre.treat <- data.frame(MDS1 = bray.nmds.pre$points[,1], MDS2 = bray.nmds.pre$points[,2],
                        Group = sample_data(physeq.pre)$Elip.treat)
plot.new()
elip.ord.pre.treat <- ordiellipse(bray.nmds.pre, sample_data(physeq.pre)$Elip.treat, display="sites", kind="se", conf=0.95, label=T)
elip.pre.treat.df <- data.frame()
for(i in levels(elip.nmds.pre.treat$Group)){
  elip.pre.treat.df <- rbind(elip.pre.treat.df, cbind(as.data.frame(with(elip.nmds.pre.treat[elip.nmds.pre.treat$Group==i,],
                                                     veganCovEllipse(elip.ord.pre.treat[[i]]$cov,
                                                                     elip.ord.pre.treat[[i]]$center,
                                                                     elip.ord.pre.treat[[i]]$scale))),
                                  group=i))
  
}

# Plot w/ treatment ellip
plot_ordination(physeq=physeq.pre, ordination=bray.nmds.pre, color="Treatment") +
  geom_path(data=elip.pre.treat.df, aes(x=NMDS1, y=NMDS2, colour=group), size=1, linetype=1) +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2"))




# Sex Ellipses
sample_data(physeq.pre)$Elip.sex <- paste(sample_data(physeq.pre)$Sex)
elip.nmds.pre.sex <- data.frame(MDS1 = bray.nmds.pre$points[,1], MDS2 = bray.nmds.pre$points[,2],
                        Group = sample_data(physeq.pre)$Elip.sex)
plot.new()
elip.ord.pre.sex <- ordiellipse(bray.nmds.pre, sample_data(physeq.pre)$Elip.sex, display="sites", kind="se", conf=0.95, label=T)
elip.pre.sex.df <- data.frame()
for(i in levels(elip.nmds.pre.sex$Group)){
  elip.pre.sex.df <- rbind(elip.pre.sex.df, cbind(as.data.frame(with(elip.nmds.pre.sex[elip.nmds.pre.sex$Group==i,],
                                                     veganCovEllipse(elip.ord.pre.sex[[i]]$cov,
                                                                     elip.ord.pre.sex[[i]]$center,
                                                                     elip.ord.pre.sex[[i]]$scale))),
                                  group=i))
}

# Plot w/ sex ellip
plot_ordination(physeq=physeq.pre, ordination=bray.nmds.pre, color="Sex") +
  geom_path(data=elip.pre.sex.df, aes(x=NMDS1, y=NMDS2, colour=group), size=1, linetype=1)


















### Post-treatment
bray.nmds.post <- ordinate(physeq=physeq.post, method="NMDS", distance="bray")
  # stress = 8.309702e-05

post.nmds <- plot_ordination(physeq=physeq.post, ordination=bray.nmds.post, color="Treatment", shape="Sex") +
  scale_color_manual(values=c("rosybrown", "brown2", "limegreen", "dodgerblue2")) +
  scale_shape_manual(values=c(19,2)) +
  ggtitle("Post-treatment") +
  #geom_point(size=2, stroke=1.5) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(family="Arial", size=8),
        axis.text.y = element_text(family="Arial", size=8),
        axis.title.x = element_text(family="Arial", size=8, face="bold"),
        axis.title.y = element_text(family="Arial", size=8, face="bold"),
        legend.title = element_text(family="Arial", size=10, face="bold"),
        legend.text = element_text(family="Arial", size=10),
        plot.title = element_text(family = "Arial", size=10, face="bold", hjust=0.5)
        ) +
  annotate("text", x = 0.15, y = -3e-04, label = "stress = 0.00008", size=2, family="Arial") +
  guides(colour=FALSE, shape=FALSE)











### Post-treatment w/o Low Fat
bray.nmds.post.rem <- ordinate(physeq=physeq.post.rem, method="NMDS", distance="bray")
  # stress = 0.1981966 

post.rem.nmds <- plot_ordination(physeq=physeq.post.rem, ordination=bray.nmds.post.rem, color="Treatment",
                                 shape="Sex") +
  scale_color_manual(values=c("brown2", "limegreen", "dodgerblue2")) +
  scale_shape_manual(values=c(19,2)) +
  ggtitle("Post-treatment (no Low Fat)") +
  #geom_point(size=2, stroke=1.5) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(family="Arial", size=8),
        axis.text.y = element_text(family="Arial", size=8),
        axis.title.x = element_text(family="Arial", size=8, face="bold"),
        axis.title.y = element_text(family="Arial", size=8, face="bold"),
        legend.title = element_text(family="Arial", size=10, face="bold"),
        legend.text = element_text(family="Arial", size=10),
        plot.title = element_text(family = "Arial", size=10, face="bold", hjust=0.5)
        ) +
  #guides(colour = guide_legend(order = 1), 
  #            shape = guide_legend(order = 2)) +
  annotate("text", x = 0.23, y = -0.26, label = "stress = 0.198", size=2, family="Arial") +
  guides(colour=FALSE, shape=FALSE)

# Treatment Ellipses
sample_data(physeq.post.rem)$Elip.treat <- paste(sample_data(physeq.post.rem)$Treatment)
elip.nmds.post.rem.treat <- data.frame(MDS1 = bray.nmds.post.rem$points[,1], MDS2 = bray.nmds.post.rem$points[,2],
                        Group = sample_data(physeq.post.rem)$Elip.treat)
plot.new()
elip.ord.post.rem.treat <- ordiellipse(bray.nmds.post.rem, sample_data(physeq.post.rem)$Elip.treat, display="sites", kind="se", conf=0.95, label=T)
elip.post.rem.treat.df <- data.frame()
for(i in levels(elip.nmds.post.rem.treat$Group)){
  elip.post.rem.treat.df <- rbind(elip.post.rem.treat.df, cbind(as.data.frame(with(elip.nmds.post.rem.treat[elip.nmds.post.rem.treat$Group==i,],
                                                     veganCovEllipse(elip.ord.post.rem.treat[[i]]$cov,
                                                                     elip.ord.post.rem.treat[[i]]$center,
                                                                     elip.ord.post.rem.treat[[i]]$scale))),
                                  group=i))
  
}

# Plot w/ treatment ellip
plot_ordination(physeq=physeq.post.rem, ordination=bray.nmds.post.rem, color="Treatment") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2")) +
  geom_path(data=elip.post.rem.treat.df, aes(x=NMDS1, y=NMDS2, colour=group), size=1, linetype=1)

# Sex Ellipses
sample_data(physeq.post.rem)$Elip.sex <- paste(sample_data(physeq.post.rem)$Sex)
elip.nmds.post.rem.sex <- data.frame(MDS1 = bray.nmds.post.rem$points[,1], MDS2 = bray.nmds.post.rem$points[,2],
                        Group = sample_data(physeq.post.rem)$Elip.sex)
plot.new()
elip.ord.post.rem.sex <- ordiellipse(bray.nmds.post.rem, sample_data(physeq.post.rem)$Elip.sex, display="sites", kind="se", conf=0.95, label=T)
elip.post.rem.sex.df <- data.frame()
for(i in levels(elip.nmds.post.rem.sex$Group)){
  elip.post.rem.sex.df <- rbind(elip.post.rem.sex.df, cbind(as.data.frame(with(elip.nmds.post.rem.sex[elip.nmds.post.rem.sex$Group==i,],
                                                     veganCovEllipse(elip.ord.post.rem.sex[[i]]$cov,
                                                                     elip.ord.post.rem.sex[[i]]$center,
                                                                     elip.ord.post.rem.sex[[i]]$scale))),
                                  group=i))
}

# Plot w/ sex ellip
plot_ordination(physeq=physeq.post.rem, ordination=bray.nmds.post.rem, color="Sex") +
  #scale_fill_manual(values=c("#e41a1c", "#377eb8", "#4daf4a", "#984ea3", "#f781bf", "#a65628", "#ffff33", "#ff7f00")) +
  geom_path(data=elip.post.rem.sex.df, aes(x=NMDS1, y=NMDS2, colour=group), size=1, linetype=1)



```
### NMDS Plot
```{r}
tiff("nmds.tiff", width=85, height = 150, units="mm", res = 600)
grid.newpage()
pushViewport(viewport(layout=(grid.layout(6,2, widths=c(1,0.38), heights=c(0.07, 1, 0.07, 1, 0.07, 1)))))
grid.text("A", x=unit(0.03, "npc"), vp=viewport(layout.pos.row=1, layout.pos.col=1),
          gp=gpar(fontsize=12,fontface="bold",fontfamily="Arial"))
print(pre.nmds, vp=viewport(layout.pos.row=2, layout.pos.col=1))
grid.text("B", x=unit(0.03, "npc"), vp=viewport(layout.pos.row=3, layout.pos.col=1),
          gp=gpar(fontsize=12,fontface="bold",fontfamily="Arial"))
print(post.nmds, vp=viewport(layout.pos.row=4, layout.pos.col=1))
grid.text("C", x=unit(0.03, "npc"), vp=viewport(layout.pos.row=5, layout.pos.col=1),
          gp=gpar(fontsize=12,fontface="bold",fontfamily="Arial"))
print(post.rem.nmds, vp=viewport(layout.pos.row=6, layout.pos.col=1))
nmds.legend$vp <- viewport(layout.pos.row = 1:6, layout.pos.col = 2)
grid.draw(nmds.legend)
dev.off()




# tiff("nmds.tiff", width=180, height = 125, units="mm", res = 600)
# grid.newpage()
# pushViewport(viewport(layout=(grid.layout(4,2, widths=c(1,1), heights=c(0.055,10,0.055,10)))))
# grid.text("A", x=unit(0.03, "npc"), vp=viewport(layout.pos.row=1, layout.pos.col=1),
#           gp=gpar(fontsize=12,fontface="bold",fontfamily="Arial"))
# print(all.nmds, vp=viewport(layout.pos.row=2, layout.pos.col=1))
# grid.text("B", x=unit(0.03, "npc"), vp=viewport(layout.pos.row=1, layout.pos.col=2),
#           gp=gpar(fontsize=12,fontface="bold",fontfamily="Arial"))
# print(pre.nmds, vp=viewport(layout.pos.row=2, layout.pos.col=2))
# grid.text("C", x=unit(0.03, "npc"), vp=viewport(layout.pos.row=3, layout.pos.col=1),
#           gp=gpar(fontsize=12,fontface="bold",fontfamily="Arial"))
# print(post.nmds, vp=viewport(layout.pos.row=4, layout.pos.col=1))
# grid.text("D", x=unit(0.03, "npc"), vp=viewport(layout.pos.row=3, layout.pos.col=2),
#           gp=gpar(fontsize=12,fontface="bold",fontfamily="Arial"))
# print(post.rem.nmds, vp=viewport(layout.pos.row=4, layout.pos.col=2))
# dev.off()

```

### PERMANOVA Bray-Curtis
```{r}
### Paired
pair.sampdf <- data.frame(sample_data(physeq.pair))
pair.bray <- phyloseq::distance(physeq=physeq.pair, method="bray")

# Time
adonis(pair.bray ~ Time, data=pair.sampdf)
  # p-value = 0.001
  # R2 = 0.25838
beta.tax = betadisper(d=pair.bray, group=pair.sampdf$Time)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.522

# Treatment
adonis(pair.bray ~ Treatment, data=pair.sampdf)
  # p-value = 0.001
  # R2 = 0.12309
beta.tax = betadisper(d=pair.bray, group=pair.sampdf$Treatment)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.663

# Sex
adonis(pair.bray ~ Sex, data=pair.sampdf)
  # p-value = 0.001
  # R2 = 0.07431
beta.tax = betadisper(d=pair.bray, group=pair.sampdf$Sex)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.338

# Subj_ID
adonis(pair.bray ~ Subj_ID, data=pair.sampdf)
  # p-value = 0.976
  # R2 = 0.42718
beta.tax = betadisper(d=pair.bray, group=pair.sampdf$Subj_ID)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.001

# Combined Variables
adonis(pair.bray ~ Time + Treatment + Sex + Subj_ID,
       data=pair.sampdf)
  ### Subj_ID must be last because it's not sig
    # If first, adonis doesn't evaluate the remainder of the model because the first variable (Subj_ID) us bit sig
  # Time: p-value = 0.001; R2 = 0.25838
  # Treatment: p-value = 0.001; R2 = 0.12309
  # Sex: p-value = 0.001; R2 = 0.07370
  # Subj_ID: p-value = 0.907, R2 = 0.23038
  # Residuals = 0.31445
adonis(pair.bray ~ Time*Treatment*Sex, data=pair.sampdf)
  # Time: p-value = 0.001, R2 = 0.25838
  # Treatment: p-value = 0.001, R2 = 0.12309
  # Sex: p-value =  0.001, R2 = 0.07370
  # Time:Treatment: p-value = 0.001, R2 = 0.09180
  # Time:Sex: p-value = 0.001, R2 = 0.05753
  # Treatment:Sex: p-value = 0.259, R2 = 0.02191
  # Time:Treatment:Sex: p-value = 0.298, R2= 0.02160
  # Residuals: R2 = 0.35198

### Pre-treatment
pre.sampdf <- data.frame(sample_data(physeq.pre))
pre.bray <- phyloseq::distance(physeq=physeq.pre, method="bray")

# Sex
adonis(pre.bray ~ Sex, data=pre.sampdf)
  # p-value = 0.001
  # R2 = 0.34423
beta.tax = betadisper(d=pre.bray, group=pre.sampdf$Sex)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.042
anosim(pre.bray, pre.sampdf$Sex)
  # p-value = 0.001
  # R = 0.8267

# Treatment
adonis(pre.bray ~ Treatment, data=pre.sampdf)
  # p-value = 0.775
  # R2 = 0.06522
beta.tax = betadisper(d=pre.bray, group=pre.sampdf$Treatment)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.931

# Combined Variables
adonis(pre.bray ~ Sex + Treatment, data=pre.sampdf)
  # Sex: p-value = 0.001; R2 = 0.34423
  # Treatment: p-value = 0.340; R2 = 0.06231
adonis(pre.bray ~ Sex*Treatment, data=pre.sampdf)
  # Sex: p-value = 0.001, R2 = 0.34423
  # Treatment: p-value = 0.367, R2 = 0.06231
  # Sex:Treatment: p-value = 0.414, R2 = 0.05765
  # Residuals = 0.53580






### Post-treatment
post.sampdf <- data.frame(sample_data(physeq.post))
post.bray <- phyloseq::distance(physeq=physeq.post, method="bray")

# Sex
adonis(post.bray ~ Sex, data=post.sampdf)
  # p-value = 0.166
  # R2 = 0.04113
beta.tax = betadisper(d=post.bray, group=post.sampdf$Sex)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.859

# Treatment
adonis(post.bray ~ Treatment, data=post.sampdf)
  # p-value = 0.001
  # R2 = 0.47417
beta.tax = betadisper(d=post.bray, group=post.sampdf$Treatment)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.001
anosim(post.bray, post.sampdf$Treatment)
  # p-value = 0.001
  # R = 0.4626


# Combined Variables
adonis(post.bray ~ Treatment + Sex, data=post.sampdf)
  # Treatment: p-value = 0.001; R2 = 0.47417
  # Sex: p-value = 0.036; R2 = 0.04196
  # Residuals = 0.48387
adonis(post.bray ~ Treatment*Sex, data=post.sampdf)
  # Treatment: p-value = 0.001, R2 = 0.47417
  # Sex: p-value = 0.025, R2 = 0.04196
  # Treatment:Sex: p-value = 0.186, R2 = 0.05951
  # Residuals = 0.42435

### Post-treatment w/o Low Fat
post.rem.sampdf <- data.frame(sample_data(physeq.post.rem))
post.rem.bray <- phyloseq::distance(physeq=physeq.post.rem, method="bray")

# Sex
adonis(post.rem.bray ~ Sex, data=post.rem.sampdf)
  # p-value = 0.003
  # R2 = 0.1325
beta.tax = betadisper(d=post.rem.bray, group=post.rem.sampdf$Sex)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.345

# Treatment
adonis(post.rem.bray ~ Treatment, data=post.rem.sampdf)
  # p-value = 0.033
  # R2 = 0.12945
beta.tax = betadisper(d=post.rem.bray, group=post.rem.sampdf$Treatment)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.486

# Combined Variables
adonis(post.rem.bray ~ Sex + Treatment, data=post.rem.sampdf)
  # Sex: p-value = 0.002; R2 = 0.13250
  # Treatment: p-value = 0.010; R2 = 0.13259
adonis(post.rem.bray ~ Treatment*Sex, data=post.rem.sampdf)
  # Treatment: p-value = 0.014, R2 = 0.12945
  # Sex: p-value = 0.001, R2 = 0.13564
  # Treatment:Sex: p-value = 0.474, R2 = 0.06651
  # Residuals = 0.66840




### All Female
fem.sampdf <- data.frame(sample_data(physeq.fem))
fem.bray <- phyloseq::distance(physeq=physeq.fem, method="bray")

# Time
adonis(fem.bray ~ Time, data=fem.sampdf)
  # p-value = 0.001
  # R2 = 0.35979
beta.tax = betadisper(d=fem.bray, group=fem.sampdf$Time)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.03

# Treatment
adonis(fem.bray ~ Treatment, data=fem.sampdf)
  # p-value = 0.036
  # R2 = 0.16207
beta.tax = betadisper(d=fem.bray, group=fem.sampdf$Treatment)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.102

# Subj_ID
adonis(fem.bray ~ Subj_ID, data=fem.sampdf)
  # p-value = 0.977
  # R2 = 0.37156
beta.tax = betadisper(d=fem.bray, group=fem.sampdf$Subj_ID)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.001

# Combined Variables
adonis(fem.bray ~ Time + Treatment + Subj_ID, data=fem.sampdf)
  # Time: p-value = 0.001; R2 = 0.35979
  # Treatment: p-value = 0.001; R2 = 0.16207
  # Subj_ID: p-value = 0.560; R2 = 0.20949



### All Male
mal.sampdf <- data.frame(sample_data(physeq.mal))
mal.bray <- phyloseq::distance(physeq=physeq.mal, method="bray")

# Time
adonis(mal.bray ~ Time, data=mal.sampdf)
  # p-value = 0.001
  # R2 = 0.32399
beta.tax = betadisper(d=mal.bray, group=mal.sampdf$Time)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.149

# Treatment
adonis(mal.bray ~ Treatment, data=mal.sampdf)
  # p-value = 0.021
  # R2 = 0.1503
beta.tax = betadisper(d=mal.bray, group=mal.sampdf$Treatment)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.761

# Subj_ID
adonis(mal.bray ~ Subj_ID, data=mal.sampdf)
  # p-value = 0.976
  # R2 = 0.39022
beta.tax = betadisper(d=mal.bray, group=mal.sampdf$Subj_ID)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.001

# Combined Variables
adonis(mal.bray ~ Time + Treatment + Subj_ID, data=mal.sampdf)
  # Time: p-value = 0.001; R2 = 0.32399
  # Treatment: p-value = 0.001; R2 = 0.15030
  # Subj_ID: p-value = 0.442; R2 = 0.23992



### Female Pre-treatment
pre.fem.sampdf <- data.frame(sample_data(physeq.pre.fem))
pre.fem.bray <- phyloseq::distance(physeq=physeq.pre.fem, method="bray")

# Treatment
adonis(pre.fem.bray ~ Treatment, data=pre.fem.sampdf)
  # p-value = 0.565
  # R2 = 0.15532
beta.tax = betadisper(d=pre.fem.bray, group=pre.fem.sampdf$Treatment)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.456



### Male Pre-treatment
pre.mal.sampdf <- data.frame(sample_data(physeq.pre.mal))
pre.mal.bray <- phyloseq::distance(physeq=physeq.pre.mal, method="bray")

# Treatment
adonis(pre.mal.bray ~ Treatment, data=pre.mal.sampdf)
  # p-value = 0.241
  # R2 = 0.20338
beta.tax = betadisper(d=pre.mal.bray, group=pre.mal.sampdf$Treatment)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.886



### Female Post-treatment
post.fem.sampdf <- data.frame(sample_data(physeq.post.fem))
post.fem.bray <- phyloseq::distance(physeq=physeq.post.fem, method="bray")

# Treatment
adonis(post.fem.bray ~ Treatment, data=post.fem.sampdf)
  # p-value = 0.001
  # R2 = 0.60409
beta.tax = betadisper(d=post.fem.bray, group=post.fem.sampdf$Treatment)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.112



### Male Post-treatment
post.mal.sampdf <- data.frame(sample_data(physeq.post.mal))
post.mal.bray <- phyloseq::distance(physeq=physeq.post.mal, method="bray")

# Treatment
adonis(post.mal.bray ~ Treatment, data=post.mal.sampdf)
  # p-value = 0.001
  # R2 = 0.51171
beta.tax = betadisper(d=post.mal.bray, group=post.mal.sampdf$Treatment)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.004



### Female Post-treatment w/o Low Fat
post.fem.rem.sampdf <- data.frame(sample_data(physeq.post.fem.rem))
post.fem.rem.bray <- phyloseq::distance(physeq=physeq.post.fem.rem, method="bray")

# Treatment
adonis(post.fem.rem.bray ~ Treatment, data=post.fem.rem.sampdf)
  # p-value = 0.038
  # R2 = 0.27097
beta.tax = betadisper(d=post.fem.rem.bray, group=post.fem.rem.sampdf$Treatment)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.992



### Male Post-treatment w/o Low Fat
post.mal.rem.sampdf <- data.frame(sample_data(physeq.post.mal.rem))
post.mal.rem.bray <- phyloseq::distance(physeq=physeq.post.mal.rem, method="bray")

# Treatment
adonis(post.mal.rem.bray ~ Treatment, data=post.mal.rem.sampdf)
  # p-value = 0.263
  # R2 = 0.19267
beta.tax = betadisper(d=post.mal.rem.bray, group=post.mal.rem.sampdf$Treatment)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.696

### High Fat
hf.sampdf <- data.frame(sample_data(physeq.hf))
hf.bray <- phyloseq::distance(physeq=physeq.hf, method="bray")

# Time
adonis(hf.bray ~ Time, data=hf.sampdf)
  # p-value = 0.001
  # R2 = 0.48394
beta.tax = betadisper(d=hf.bray, group=hf.sampdf$Time)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.005

# Sex
adonis(hf.bray ~ Sex, data=hf.sampdf)
  # p-value = 0.188
  # R2 = 0.08379
beta.tax = betadisper(d=hf.bray, group=hf.sampdf$Sex)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.595

# Subj_ID
adonis(hf.bray ~ Subj_ID, data=hf.sampdf)
  # p-value = 0.986
  # R2 = 0.28542
beta.tax = betadisper(d=hf.bray, group=hf.sampdf$Subj_ID)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.001

# Combined
adonis(hf.bray ~ Time + Sex + Subj_ID, data=hf.sampdf)
  # Time: p-value = 0.001; R2 = 0.48394
  # Sex: p-value = 0.038; R2 = 0.08379
  # Subj_ID: p-value = 0.471; R2 = 0.20163



### Low Fat
lf.sampdf <- data.frame(sample_data(physeq.lf))
lf.bray <- phyloseq::distance(physeq=physeq.lf, method="bray")

# Time
adonis(lf.bray ~ Time, data=lf.sampdf)
  # p-value = 0.001
  # R2 = 0.20248
beta.tax = betadisper(d=lf.bray, group=lf.sampdf$Time)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.528

# Sex
adonis(lf.bray ~ Sex, data=lf.sampdf)
  # p-value = 0.001
  # R2 = 0.14304
beta.tax = betadisper(d=lf.bray, group=lf.sampdf$Sex)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.169

# Subj_ID
adonis(lf.bray ~ Subj_ID, data=lf.sampdf)
  # p-value = 0.45
  # R2 = 0.46743
beta.tax = betadisper(d=lf.bray, group=lf.sampdf$Subj_ID)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.001

# Combined
adonis(lf.bray ~ Time + Sex + Subj_ID, data=lf.sampdf)
  # Time: p-value = 0.001; R2 = 0.20248
  # Sex: p-value = 0.001; R2 = 0.14304
  # Subj_ID: p-value = 0.303; R2 = 0.32439



### Saccharin
sc.sampdf <- data.frame(sample_data(physeq.sc))
sc.bray <- phyloseq::distance(physeq=physeq.sc, method="bray")

# Time
adonis(sc.bray ~ Time, data=sc.sampdf)
  # p-value = 0.002
  # R2 = 0.43652
beta.tax = betadisper(d=sc.bray, group=sc.sampdf$Time)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.007

# Sex
adonis(sc.bray ~ Sex, data=sc.sampdf)
  # p-value = 0.149
  # R2 = 0.09876
beta.tax = betadisper(d=sc.bray, group=sc.sampdf$Sex)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.815

# Subj_ID
adonis(sc.bray ~ Subj_ID, data=sc.sampdf)
  # p-value = 0.966
  # R2 = 0.33888
beta.tax = betadisper(d=sc.bray, group=sc.sampdf$Subj_ID)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.001

# Combined
adonis(sc.bray ~ Time + Sex + Subj_ID, data=sc.sampdf)
  # Time: p-value = 0.001; R2 = 0.43652
  # Sex: p-value = 0.016; R2 = 0.09876
  # Subj_ID: p-value = 0.303; R2 = 0.24012



### Stevia
tv.sampdf <- data.frame(sample_data(physeq.tv))
tv.bray <- phyloseq::distance(physeq=physeq.tv, method="bray")

# Time
adonis(tv.bray ~ Time, data=tv.sampdf)
  # p-value = 0.001
  # R2 = 0.48081
beta.tax = betadisper(d=tv.bray, group=tv.sampdf$Time)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.001

# Sex
adonis(tv.bray ~ Sex, data=tv.sampdf)
  # p-value = 0.165
  # R2 = 0.11129
beta.tax = betadisper(d=tv.bray, group=tv.sampdf$Sex)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.512

# Subj_ID
adonis(tv.bray ~ Subj_ID, data=tv.sampdf)
  # p-value = 0.985
  # R2 = 0.29089
beta.tax = betadisper(d=tv.bray, group=tv.sampdf$Subj_ID)
p <- permutest(beta.tax)
p$tab
  # p-value = 0.001

# Combined
adonis(tv.bray ~ Time + Sex + Subj_ID, data=tv.sampdf)
  # Time: p-value = 0.001; R2 = 0.48081
  # Sex: p-value = 0.017; R2 = 0.11129
  # Subj_ID: p-value = 0.580; R2 = 0.17960

combos <- combn(x=levels(pair.sampdf$Treatment), m=2)
bray.pvals.pre <- data.frame(rep(999,6))
for( i in 1:ncol(combos)){
  temp.physeq <- subset_samples(physeq.pre, Treatment %in% combos[,i])
  temp.sampdf <- data.frame(sample_data(temp.physeq))
  temp.bray <- phyloseq::distance(physeq=temp.physeq, method="bray")
  test <- adonis(temp.bray ~ Group, data=temp.sampdf)
  rownames(bray.pvals.pre)[i] <- paste(combos[1,i], combos[2,i])
  bray.pvals.pre[i,1]<- test[[1]]$`Pr(>F)`[1]
}
colnames(bray.pvals.pre) <- "pval"
bray.pvals.pre$Adj.bonf <- p.adjust(bray.pvals.pre$pval, method="bonferroni")
bray.pvals.pre$Adj.BH <- p.adjust(bray.pvals.pre$pval, method="BH")

bray.pvals.post <- data.frame(rep(999,6))
for( i in 1:ncol(combos)){
  temp.physeq <- subset_samples(physeq.post, Treatment %in% combos[,i])
  temp.sampdf <- data.frame(sample_data(temp.physeq))
  temp.bray <- phyloseq::distance(physeq=temp.physeq, method="bray")
  test <- adonis(temp.bray ~ Group, data=temp.sampdf)
  rownames(bray.pvals.post)[i] <- paste(combos[1,i], combos[2,i])
  bray.pvals.post[i,1]<- test[[1]]$`Pr(>F)`[1]
}
colnames(bray.pvals.post) <- "pval"
bray.pvals.post$Adj.bonf <- p.adjust(bray.pvals.post$pval, method="bonferroni")
bray.pvals.post$Adj.BH <- p.adjust(bray.pvals.post$pval, method="BH")

bray.pvals.pre.fem <- data.frame(rep(999,6))
for( i in 1:ncol(combos)){
  temp.physeq <- subset_samples(physeq.pre.fem, Treatment %in% combos[,i])
  temp.sampdf <- data.frame(sample_data(temp.physeq))
  temp.bray <- phyloseq::distance(physeq=temp.physeq, method="bray")
  test <- adonis(temp.bray ~ Group, data=temp.sampdf)
  rownames(bray.pvals.pre.fem)[i] <- paste(combos[1,i], combos[2,i])
  bray.pvals.pre.fem[i,1]<- test[[1]]$`Pr(>F)`[1]
}
colnames(bray.pvals.pre.fem) <- "pval"
bray.pvals.pre.fem$Adj.bonf <- p.adjust(bray.pvals.pre.fem$pval, method="bonferroni")
bray.pvals.pre.fem$Adj.BH <- p.adjust(bray.pvals.pre.fem$pval, method="BH")

bray.pvals.pre.mal <- data.frame(rep(999,6))
for( i in 1:ncol(combos)){
  temp.physeq <- subset_samples(physeq.pre.mal, Treatment %in% combos[,i])
  temp.sampdf <- data.frame(sample_data(temp.physeq))
  temp.bray <- phyloseq::distance(physeq=temp.physeq, method="bray")
  test <- adonis(temp.bray ~ Group, data=temp.sampdf)
  rownames(bray.pvals.pre.mal)[i] <- paste(combos[1,i], combos[2,i])
  bray.pvals.pre.mal[i,1]<- test[[1]]$`Pr(>F)`[1]
}
colnames(bray.pvals.pre.mal) <- "pval"
bray.pvals.pre.mal$Adj.bonf <- p.adjust(bray.pvals.pre.mal$pval, method="bonferroni")
bray.pvals.pre.mal$Adj.BH <- p.adjust(bray.pvals.pre.mal$pval, method="BH")

bray.pvals.post.fem <- data.frame(rep(999,6))
for( i in 1:ncol(combos)){
  temp.physeq <- subset_samples(physeq.post.fem, Treatment %in% combos[,i])
  temp.sampdf <- data.frame(sample_data(temp.physeq))
  temp.bray <- phyloseq::distance(physeq=temp.physeq, method="bray")
  test <- adonis(temp.bray ~ Group, data=temp.sampdf)
  rownames(bray.pvals.post.fem)[i] <- paste(combos[1,i], combos[2,i])
  bray.pvals.post.fem[i,1]<- test[[1]]$`Pr(>F)`[1]
}
colnames(bray.pvals.post.fem) <- "pval"
bray.pvals.post.fem$Adj.bonf <- p.adjust(bray.pvals.post.fem$pval, method="bonferroni")
bray.pvals.post.fem$Adj.BH <- p.adjust(bray.pvals.post.fem$pval, method="BH")

bray.pvals.post.mal <- data.frame(rep(999,6))
for( i in 1:ncol(combos)){
  temp.physeq <- subset_samples(physeq.post.mal, Treatment %in% combos[,i])
  temp.sampdf <- data.frame(sample_data(temp.physeq))
  temp.bray <- phyloseq::distance(physeq=temp.physeq, method="bray")
  test <- adonis(temp.bray ~ Group, data=temp.sampdf)
  rownames(bray.pvals.post.mal)[i] <- paste(combos[1,i], combos[2,i])
  bray.pvals.post.mal[i,1]<- test[[1]]$`Pr(>F)`[1]
}
colnames(bray.pvals.post.mal) <- "pval"
bray.pvals.post.mal$Adj.bonf <- p.adjust(bray.pvals.post.mal$pval, method="bonferroni")
bray.pvals.post.mal$Adj.BH <- p.adjust(bray.pvals.post.mal$pval, method="BH")



### Adjust P-vals
bray.pvals.all <- data.frame(bray.pvals.pre[,1])
bray.pvals.all[(nrow(bray.pvals.all)+1):(nrow(bray.pvals.all)+nrow(bray.pvals.post)),1] <- bray.pvals.post[,1]
bray.pvals.all[(nrow(bray.pvals.all)+1):(nrow(bray.pvals.all)+nrow(bray.pvals.pre.fem)),1] <- bray.pvals.pre.fem[,1]
bray.pvals.all[(nrow(bray.pvals.all)+1):(nrow(bray.pvals.all)+nrow(bray.pvals.pre.mal)),1] <- bray.pvals.pre.mal[,1]
bray.pvals.all[(nrow(bray.pvals.all)+1):(nrow(bray.pvals.all)+nrow(bray.pvals.post.fem)),1] <- bray.pvals.post.fem[,1]
bray.pvals.all[(nrow(bray.pvals.all)+1):(nrow(bray.pvals.all)+nrow(bray.pvals.post.mal)),1] <- bray.pvals.post.mal[,1]
bray.pvals.all[(nrow(bray.pvals.all)+1),1] <- adonis(hf.bray ~ Time, data=hf.sampdf)$aov.tab[1,6]
bray.pvals.all[(nrow(bray.pvals.all)+1),1] <- adonis(lf.bray ~ Time, data=lf.sampdf)$aov.tab[1,6]
bray.pvals.all[(nrow(bray.pvals.all)+1),1] <- adonis(sc.bray ~ Time, data=sc.sampdf)$aov.tab[1,6]
bray.pvals.all[(nrow(bray.pvals.all)+1),1] <- adonis(tv.bray ~ Time, data=tv.sampdf)$aov.tab[1,6]
bray.pvals.all[nrow(bray.pvals.all)+1,1] <- adonis(pre.bray ~ Sex, data=pre.sampdf)[[1]]$`Pr(>F)`[1]
bray.pvals.all[nrow(bray.pvals.all)+1,1] <- adonis(post.bray ~ Sex, data=post.sampdf)[[1]]$`Pr(>F)`[1]
colnames(bray.pvals.all) <- "pvals"
bray.pvals.all$BH <- p.adjust(bray.pvals.all$pval, method="BH")
bray.pvals.all$Group <- c(rep("Pre", 6), rep("Post", 6), rep("Pre Fem", 6), rep("Pre Mal", 6), rep("Post Fem", 6), rep("Post Mal", 6), "High Fat", "Low Fat", "Saccharin", "Stevia", "Pre", "Post")
bray.pvals.all$Comp <- c(rownames(bray.pvals.pre), rownames(bray.pvals.post), rownames(bray.pvals.pre.fem), rownames(bray.pvals.pre.mal), rownames(bray.pvals.post.fem), rownames(bray.pvals.post.mal), rep("Time", 4), rep("Sex",2))

write.table(bray.pvals.all, "PERMANOVA.pvals2.csv", sep=",")




### Updated Adj Pvals
# Compare within each treatment, Pre vs. Post
p.adjust(c(0.001, 0.001, 0.002, 0.001), method="BH")
  # LF, HF, SC, TV
  # 0.001333333 0.001333333 0.002000000 0.001333333
# Pre-treatment tests
p.adjust(c(0.001, 0.775), method="BH")
  # Sex, Treatment
  # 0.002, 0.775
# Post-treatment tests
p.adjust(c(0.001, 0.035), method="BH")
  # Sex, Treatment
# Post-treatment, testing sex within each treatment
p.adjust(c(0.006, 0.007, 0.005, 0.069, 0.824, 0.404, 0.009, 0.007, 0.008, 0.138, 0.391, 0.031), method="BH")
  # Male LF-HF, Male LF-SC, Male LF-TV, Male HF-SC, Male HF-TV, Male SC-TV, Female LF-HF, Female LF-SC, Female LF-TV, Female HF-SC, Female HF-TV, Female SC-TV5
```











### Simper (OTU-level)
```{r}
### OTU-Level

# All
# simper.pretty(data.frame(otu_table(physeq.pair)),
#               data.frame(sample_data(physeq.pair)),
#               c("Treatment", "Time", "Sex"),
#               perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
#               output_name='stevia')
# stevia.simper <- read.csv("stevia_clean_simper.csv")
# kruskal.pretty(data.frame(otu_table(physeq.pair)),
#                data.frame(sample_data(physeq.pair)),
#                csv = stevia.simper,
#                c("Treatment", "Time", "Sex"),
#                output_name = 'stevia',
#                taxonomy = data.frame(tax_table(physeq.pair)))
stevia.simper.kw <- read.csv("Simper_OTU/stevia_krusk_simper.csv")
for(i in 1:nrow(stevia.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.pair))) == stevia.simper.kw$OTU[i])
  stevia.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.pair))[save,2], "-",
          data.frame(tax_table(physeq.pair))[save,3], "-",
          data.frame(tax_table(physeq.pair))[save,4], "-",
          data.frame(tax_table(physeq.pair))[save,5], "-",
          data.frame(tax_table(physeq.pair))[save,6])
}
write.table(stevia.simper.kw, "stevia_krusk_simper.csv", sep=",")

# Pre-treatment
simper.pretty(data.frame(otu_table(physeq.pre)),
              data.frame(sample_data(physeq.pre)),
              c("Sex"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.pre')
stevia.pre.simper <- read.csv("stevia.pre_sex_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.pre)),
               data.frame(sample_data(physeq.pre)),
               csv = stevia.pre.simper,
               c("Sex"),
               output_name = 'stevia.pre_sex',
               taxonomy = data.frame(tax_table(physeq.pre)))
stevia.pre.simper.kw <- read.csv("Simper_OTU/stevia.pre_sex_krusk_simper.csv")
for(i in 1:nrow(stevia.pre.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.pre))) == stevia.pre.simper.kw$OTU[i])
  stevia.pre.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.pre))[save,2], "-",
          data.frame(tax_table(physeq.pre))[save,3], "-",
          data.frame(tax_table(physeq.pre))[save,4], "-",
          data.frame(tax_table(physeq.pre))[save,5], "-",
          data.frame(tax_table(physeq.pre))[save,6])
}
#write.table(stevia.pre.simper.kw, "Simper_OTU/stevia.pre_sex_krusk_simper.csv", sep=",")

# Post-treatment - Treatment
simper.pretty(data.frame(otu_table(physeq.post)),
              data.frame(sample_data(physeq.post)),
              c("Treatment"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.post_treat')
stevia.post.simper <- read.csv("stevia.post_treat_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.post)),
               data.frame(sample_data(physeq.post)),
               csv = stevia.post.simper,
               c("Treatment"),
               output_name = 'stevia.post_treat',
               taxonomy = data.frame(tax_table(physeq.post)))
stevia.post.simper.kw <- read.csv("stevia.post_treat_krusk_simper.csv")
for(i in 1:nrow(stevia.post.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.post))) == stevia.post.simper.kw$OTU[i])
  stevia.post.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.post))[save,2], "-",
          data.frame(tax_table(physeq.post))[save,3], "-",
          data.frame(tax_table(physeq.post))[save,4], "-",
          data.frame(tax_table(physeq.post))[save,5], "-",
          data.frame(tax_table(physeq.post))[save,6])
}
#write.table(stevia.post.simper.kw, "stevia.post_treat_krusk_simper.csv", sep=",")


# Post-treatment - Sex
simper.pretty(data.frame(otu_table(physeq.post)),
              data.frame(sample_data(physeq.post)),
              c("Sex"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.post_sex')
stevia.post.simper <- read.csv("stevia.post_sex_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.post)),
               data.frame(sample_data(physeq.post)),
               csv = stevia.post.simper,
               c("Sex"),
               output_name = 'stevia.post_sex',
               taxonomy = data.frame(tax_table(physeq.post)))
stevia.post.simper.kw <- read.csv("stevia.post_sex_krusk_simper.csv")
for(i in 1:nrow(stevia.post.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.post))) == stevia.post.simper.kw$OTU[i])
  stevia.post.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.post))[save,2], "-",
          data.frame(tax_table(physeq.post))[save,3], "-",
          data.frame(tax_table(physeq.post))[save,4], "-",
          data.frame(tax_table(physeq.post))[save,5], "-",
          data.frame(tax_table(physeq.post))[save,6])
}
write.table(stevia.post.simper.kw, "stevia.post_sex_krusk_simper.csv", sep=",")


# High Fat
simper.pretty(data.frame(otu_table(physeq.hf)),
              data.frame(sample_data(physeq.hf)),
              c("Time"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.hf_time')
stevia.hf.simper <- read.csv("stevia.hf_time_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.hf)),
               data.frame(sample_data(physeq.hf)),
               csv = stevia.hf.simper,
               c("Time"),
               output_name = 'stevia.hf_time',
               taxonomy = data.frame(tax_table(physeq.hf)))
stevia.hf.simper.kw <- read.csv("Simper_OTU/stevia.hf_time_krusk_simper.csv")
for(i in 1:nrow(stevia.hf.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.hf))) == stevia.hf.simper.kw$OTU[i])
  stevia.hf.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.hf))[save,2], "-",
          data.frame(tax_table(physeq.hf))[save,3], "-",
          data.frame(tax_table(physeq.hf))[save,4], "-",
          data.frame(tax_table(physeq.hf))[save,5], "-",
          data.frame(tax_table(physeq.hf))[save,6])
}
#write.table(stevia.hf.simper.kw, "Simper_OTU/stevia.hf_time_krusk_simper.csv", sep=",")

# Low Fat
simper.pretty(data.frame(otu_table(physeq.lf)),
              data.frame(sample_data(physeq.lf)),
              c("Time"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.lf_time')
stevia.lf.simper <- read.csv("stevia.lf_time_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.lf)),
               data.frame(sample_data(physeq.lf)),
               csv = stevia.lf.simper,
               c("Time"),
               output_name = 'stevia.lf_time',
               taxonomy = data.frame(tax_table(physeq.lf)))
stevia.lf.simper.kw <- read.csv("Simper_OTU/stevia.lf_time_krusk_simper.csv")
for(i in 1:nrow(stevia.lf.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.lf))) == stevia.lf.simper.kw$OTU[i])
  stevia.lf.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.lf))[save,2], "-",
          data.frame(tax_table(physeq.lf))[save,3], "-",
          data.frame(tax_table(physeq.lf))[save,4], "-",
          data.frame(tax_table(physeq.lf))[save,5], "-",
          data.frame(tax_table(physeq.lf))[save,6])
}
#write.table(stevia.lf.simper.kw, "Simper_OTU/stevia.lf_time_krusk_simper.csv", sep=",")

# Saccharin
simper.pretty(data.frame(otu_table(physeq.sc)),
              data.frame(sample_data(physeq.sc)),
              c("Time"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.sc_time')
stevia.sc.simper <- read.csv("stevia.sc_time_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.sc)),
               data.frame(sample_data(physeq.sc)),
               csv = stevia.sc.simper,
               c("Time"),
               output_name = 'stevia.sc_time',
               taxonomy = data.frame(tax_table(physeq.sc)))
stevia.sc.simper.kw <- read.csv("Simper_OTU/stevia.sc_time_krusk_simper.csv")
for(i in 1:nrow(stevia.sc.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.sc))) == stevia.sc.simper.kw$OTU[i])
  stevia.sc.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.sc))[save,2], "-",
          data.frame(tax_table(physeq.sc))[save,3], "-",
          data.frame(tax_table(physeq.sc))[save,4], "-",
          data.frame(tax_table(physeq.sc))[save,5], "-",
          data.frame(tax_table(physeq.sc))[save,6])
}
#write.table(stevia.sc.simper.kw, "Simper_OTU/stevia.sc_time_krusk_simper.csv", sep=",")

# Stevia
simper.pretty(data.frame(otu_table(physeq.tv)),
              data.frame(sample_data(physeq.tv)),
              c("Time"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.tv_time')
stevia.tv.simper <- read.csv("stevia.tv_time_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.tv)),
               data.frame(sample_data(physeq.tv)),
               csv = stevia.tv.simper,
               c("Time"),
               output_name = 'stevia.tv_time',
               taxonomy = data.frame(tax_table(physeq.tv)))
stevia.tv.simper.kw <- read.csv("Simper_OTU/stevia.tv_time_krusk_simper.csv")
for(i in 1:nrow(stevia.tv.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.tv))) == stevia.tv.simper.kw$OTU[i])
  stevia.tv.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.tv))[save,2], "-",
          data.frame(tax_table(physeq.tv))[save,3], "-",
          data.frame(tax_table(physeq.tv))[save,4], "-",
          data.frame(tax_table(physeq.tv))[save,5], "-",
          data.frame(tax_table(physeq.tv))[save,6])
}
#write.table(stevia.tv.simper.kw, "Simper_OTU/stevia.tv_time_krusk_simper.csv", sep=",")

# Post-treatment w/o Low Fat
simper.pretty(data.frame(otu_table(physeq.post.rem)),
              data.frame(sample_data(physeq.post.rem)),
              c("Sex"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.post.rem_sex')
stevia.post.simper <- read.csv("stevia.post.rem_sex_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.post.rem)),
               data.frame(sample_data(physeq.post.rem)),
               csv = stevia.post.simper,
               c("Sex"),
               output_name = 'stevia.post.rem_sex',
               taxonomy = data.frame(tax_table(physeq.post.rem)))
stevia.post.rem.simper.kw <- read.csv("Simper_OTU/stevia.post.rem_sex_krusk_simper.csv")
for(i in 1:nrow(stevia.post.rem.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.post.rem))) == stevia.post.rem.simper.kw$OTU[i])
  stevia.post.rem.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.post.rem))[save,2], "-",
          data.frame(tax_table(physeq.post.rem))[save,3], "-",
          data.frame(tax_table(physeq.post.rem))[save,4], "-",
          data.frame(tax_table(physeq.post.rem))[save,5], "-",
          data.frame(tax_table(physeq.post.rem))[save,6])
}
#write.table(stevia.post.rem.simper.kw, "Simper_OTU/stevia.post.rem_sex_krusk_simper.csv", sep=",")




### BH CORRECTION FOR ALL OTU-LEVEL SIMPER COMPARISONS
stevia.simper.kw$Group <- rep("All", nrow(stevia.simper.kw))
stevia.simper.kw$OTU <- as.character(stevia.simper.kw$OTU)
stevia.simper.kw$Comparison <- as.character(stevia.simper.kw$Comparison)
stevia.pre.simper.kw$Group <- rep("Pre", nrow(stevia.pre.simper.kw))
stevia.pre.simper.kw$OTU <- as.character(stevia.pre.simper.kw$OTU)
stevia.pre.simper.kw$Comparison <- as.character(stevia.pre.simper.kw$Comparison)
stevia.post.simper.kw$Group <- rep("Post", nrow(stevia.post.simper.kw))
stevia.post.simper.kw$OTU <- as.character(stevia.post.simper.kw$OTU)
stevia.post.simper.kw$Comparison <- as.character(stevia.post.simper.kw$Comparison)
stevia.hf.simper.kw$Group <- rep("High Fat", nrow(stevia.hf.simper.kw))
stevia.hf.simper.kw$OTU <- as.character(stevia.hf.simper.kw$OTU)
stevia.hf.simper.kw$Comparison <- as.character(stevia.hf.simper.kw$Comparison)
stevia.lf.simper.kw$Group <- rep("Low Fat", nrow(stevia.lf.simper.kw))
stevia.lf.simper.kw$OTU <- as.character(stevia.lf.simper.kw$OTU)
stevia.lf.simper.kw$Comparison <- as.character(stevia.lf.simper.kw$Comparison)
stevia.sc.simper.kw$Group <- rep("Saccharin", nrow(stevia.sc.simper.kw))
stevia.sc.simper.kw$OTU <- as.character(stevia.sc.simper.kw$OTU)
stevia.sc.simper.kw$Comparison <- as.character(stevia.sc.simper.kw$Comparison)
stevia.tv.simper.kw$Group <- rep("Stevia", nrow(stevia.tv.simper.kw))
stevia.tv.simper.kw$OTU <- as.character(stevia.tv.simper.kw$OTU)
stevia.tv.simper.kw$Comparison <- as.character(stevia.tv.simper.kw$Comparison)
#stevia.post.rem.simper.kw$Group <- rep("Post_Rem", nrow(stevia.post.rem.simper.kw))
#stevia.post.rem.simper.kw$OTU <- as.character(stevia.post.rem.simper.kw$OTU)
#stevia.post.rem.simper.kw$Comparison <- as.character(stevia.post.rem.simper.kw$Comparison)
stevia.simper.all <- stevia.simper.kw
stevia.simper.all[(nrow(stevia.simper.all)+1):(nrow(stevia.simper.all)+nrow(stevia.pre.simper.kw)),] <- stevia.pre.simper.kw
stevia.simper.all[(nrow(stevia.simper.all)+1):(nrow(stevia.simper.all)+nrow(stevia.post.simper.kw)),] <- stevia.post.simper.kw
stevia.simper.all[(nrow(stevia.simper.all)+1):(nrow(stevia.simper.all)+nrow(stevia.hf.simper.kw)),] <- stevia.hf.simper.kw
stevia.simper.all[(nrow(stevia.simper.all)+1):(nrow(stevia.simper.all)+nrow(stevia.lf.simper.kw)),] <- stevia.lf.simper.kw
stevia.simper.all[(nrow(stevia.simper.all)+1):(nrow(stevia.simper.all)+nrow(stevia.sc.simper.kw)),] <- stevia.sc.simper.kw
stevia.simper.all[(nrow(stevia.simper.all)+1):(nrow(stevia.simper.all)+nrow(stevia.tv.simper.kw)),] <- stevia.tv.simper.kw
#stevia.simper.all[(nrow(stevia.simper.all)+1):(nrow(stevia.simper.all)+nrow(stevia.post.rem.simper.kw)),] <- stevia.post.rem.simper.kw
stevia.simper.all$fdr_krusk_p.val <- p.adjust(stevia.simper.all$krusk_p.val, "BH")
#write.table(stevia.simper.all, "stevia.simper.all.csv", sep=",")





### Calculate mean rel abund for post-treatment
physeq.post.relabund <- transform_sample_counts(physeq.post, function(x){(x/sum(x))*100})
otu00003 <- subset_taxa(physeq.post.relabund, Species == "Otu00003")
otu3 <- psmelt(otu00003)
otu3.sum <- otu3 %>%
  group_by(Treatment) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00009 <- subset_taxa(physeq.post.relabund, Species == "Otu00009")
otu9 <- psmelt(otu00009)
otu9.sum <- otu9 %>%
  group_by(Treatment) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00018 <- subset_taxa(physeq.post.relabund, Species == "Otu00018")
otu18 <- psmelt(otu00018)
otu18.sum <- otu18 %>%
  group_by(Treatment) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00021 <- subset_taxa(physeq.post.relabund, Species == "Otu00021")
otu21 <- psmelt(otu00021)
otu21.sum <- otu21 %>%
  group_by(Treatment) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))





### Calculate mean rel abund for Time comparison
physeq.pair.relabund <- transform_sample_counts(physeq.pair, function(x){(x/sum(x))*100})
otu00003 <- subset_taxa(physeq.pair.relabund, Species == "Otu00003")
otu3 <- psmelt(otu00003)
otu3.sum <- otu3 %>%
  group_by(Treatment, Time) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00004 <- subset_taxa(physeq.pair.relabund, Species == "Otu00004")
otu4 <- psmelt(otu00004)
otu4.sum <- otu4 %>%
  group_by(Treatment, Time) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00005 <- subset_taxa(physeq.pair.relabund, Species == "Otu00005")
otu5 <- psmelt(otu00005)
otu5.sum <- otu5 %>%
  group_by(Treatment, Time) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00006 <- subset_taxa(physeq.pair.relabund, Species == "Otu00006")
otu6 <- psmelt(otu00006)
otu6.sum <- otu6 %>%
  group_by(Treatment, Time) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00008 <- subset_taxa(physeq.pair.relabund, Species == "Otu00008")
otu8 <- psmelt(otu00008)
otu8.sum <- otu8 %>%
  group_by(Treatment, Time) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00009 <- subset_taxa(physeq.pair.relabund, Species == "Otu00009")
otu9 <- psmelt(otu00009)
otu9.sum <- otu9 %>%
  group_by(Treatment, Time) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00010 <- subset_taxa(physeq.pair.relabund, Species == "Otu00010")
otu10 <- psmelt(otu00010)
otu10.sum <- otu10 %>%
  group_by(Treatment, Time) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00012 <- subset_taxa(physeq.pair.relabund, Species == "Otu00012")
otu12 <- psmelt(otu00012)
otu12.sum <- otu12 %>%
  group_by(Treatment, Time) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00014 <- subset_taxa(physeq.pair.relabund, Species == "Otu00014")
otu14 <- psmelt(otu00014)
otu14.sum <- otu14 %>%
  group_by(Treatment, Time) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00015 <- subset_taxa(physeq.pair.relabund, Species == "Otu00015")
otu15 <- psmelt(otu00015)
otu15.sum <- otu15 %>%
  group_by(Treatment, Time) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
otu00023 <- subset_taxa(physeq.pair.relabund, Species == "Otu00023")
otu23 <- psmelt(otu00023)
otu23.sum <- otu23 %>%
  group_by(Treatment, Time) %>%
  summarize(Mean = mean(Abundance),
            SD = sd(Abundance))
```



### SIMPER Heatmap
```{r}
### Prep Post-Treatment
physeq.simper.post <- subset_taxa(physeq.post, Species == "Otu00002" | Species == "Otu00003" | Species == "Otu00004" | Species == "Otu00008" | Species == "Otu00009" | Species == "Otu00010" | Species == "Otu00012" | Species == "Otu00014" | Species == "Otu00018" | Species == "Otu00021" | Species == "Otu00023")
physeq.simper.post.tax <- data.frame(tax_table(physeq.simper.post))
physeq.simper.post.tax$Name <- c("Akkermansia", "Bacteroides", "S24-7", "Anaeroplasma", "S24-7", "Ruminiclostridium", "Lachnospiraceae", "Lactococcus", "Lactobacillus", "S24-7", "Alistipes")
physeq.simper.post.tax <- tax_table(physeq.simper.post.tax)
taxa_names(physeq.simper.post.tax) <- taxa_names(physeq.simper.post)
simper.post.treat <- read.csv("Simper_OTU_post.csv")
simper.post.treat.hm <- simper.post.treat
rownames(simper.post.treat.hm) <- simper.post.treat.hm$OTU
simper.post.treat.hm <- simper.post.treat.hm[,-1]
simper.post.treat.hm <- simper.post.treat.hm[,-5:-7]
simper.post.sampdat <- data.frame(c("LowFat", "HighFat", "Saccharin", "Stevia"))
colnames(simper.post.sampdat) <- "Treatment"
rownames(simper.post.sampdat) <- simper.post.sampdat$Treatment
physeq.simper.post <- merge_phyloseq(otu_table(simper.post.treat.hm, taxa_are_rows=T), physeq.simper.post.tax, sample_data(simper.post.sampdat))
colnames(tax_table(physeq.simper.post)) <- 
  c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", "OTU_Classification")
physeq.simper.post <- transform_sample_counts(physeq.simper.post, function(x){x*100})
sample_data(physeq.simper.post)$Treatment <- ordered(sample_data(physeq.simper.post)$Treatment, levels=c("LowFat", "HighFat", "Saccharin", "Stevia"))

### HeatMap Post-Treatment
# http://www.roymfrancis.com/a-guide-to-elegant-tiled-heatmaps-in-r/
# https://github.com/tidyverse/ggplot2/pull/2541
post.hm <- plot_heatmap(physeq.simper.post, sample.label = "Treatment", sample.order = c("LowFat", "HighFat", "Saccharin", "Stevia"), taxa.label = "OTU_Classification", taxa.order = "Phylum", low = "#FFFFCC", high = "firebrick3", na.value = "#FFFFFC") +
  geom_tile(colour="gray40") +
  geom_text(aes(label=sprintf("%0.2f", round(Abundance, digits=2)))) +
  scale_fill_gradient(name="Relative Abundance (%)", low = "#FFFFCC", high = "firebrick3") +
  scale_x_discrete(labels = c("Low Fat", "High Fat", "Saccharin", "Stevia")) +
  scale_y_discrete(labels=c(expression(" "^ac~"Bacteroides"), expression(" "^abc~"S24-7"), 
                            expression(" "^d~"S24-7"), expression(" "^bc~"S24-7"), 
                            expression(" "^abc~"Alistipes"), expression(" "^abc~"Ruminiclostridium"),
                            expression(" "^abc~"Lachnospiraceae"), expression(" "^acde~"Lactococcus"),
                            expression(" "^c~"Lactobacillus"), expression(" "^abc~"Anaeroplasma"), 
                            expression(" "^abc~"Akkermansia"))) +
  ylab("OTU Classification") + xlab("Post-treatment Group") +
  theme(panel.border=element_blank(),
        axis.text.x = element_text(angle=50, hjust=1, vjust=1.2, family="Arial", size=10),
        axis.text.y = element_text(family="Arial", size=10),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_text(size=12, face="bold", family="Arial"),
        axis.title.y = element_text(margin = margin(t=0, r=20, b=0, l=0), size=12, face="bold", family="Arial"),
        axis.line=element_blank(),
        legend.title = element_text(family = "Arial", size=10, face="bold"),
        legend.text = element_text(family = "Arial", size=10),
        plot.title = element_text(family = "Arial", size=10, face="bold")
  ) +
  guides(fill = guide_colorbar(barheight = unit( 3 , "in" ),
                                ticks.color = "black",
                                ticks.linewidth = 1,
                                frame.color = "black",
                                frame.linewidth = 1))




### Prep Time
physeq.simper.time <- subset_taxa(physeq.pair, Species == "Otu00003" | Species == "Otu00004" | 
                                    Species == "Otu00005" | Species == "Otu00006" | Species == "Otu00008" | 
                                    Species == "Otu00009" | Species == "Otu00010" | Species == "Otu00012" | 
                                    Species == "Otu00014" | Species == "Otu00015" | Species == "Otu00023")
physeq.simper.time.tax <- data.frame(tax_table(physeq.simper.time))
physeq.simper.time.tax$Name <- c("Bacteroides", "S24-7", "S24-7", "S24-7", "Anaeroplasma", "S24-7", "Ruminiclostridium", "Lachnospiraceae", "Lactococcus", "NK4A136", "Alistipes")
physeq.simper.time.tax <- tax_table(physeq.simper.time.tax)
taxa_names(physeq.simper.time.tax) <- taxa_names(physeq.simper.time)
simper.time.treat <- read.csv("Simper_OTU_time.csv")
simper.time.treat.hm <- simper.time.treat
rownames(simper.time.treat.hm) <- simper.time.treat.hm$OTU
simper.time.treat.hm <- simper.time.treat.hm[,-1]
simper.time.treat.hm <- simper.time.treat.hm[,-9:-11]
simper.time.sampdat <- data.frame(c("LF_Pre", "LF_Post", "HF_Pre", "HF_Post", "SC_Pre", "SC_Post", "TV_Pre", "TV_Post"))
colnames(simper.time.sampdat) <- "Treatment_Time"
rownames(simper.time.sampdat) <- simper.time.sampdat$Treatment_Time
physeq.simper.time <- merge_phyloseq(otu_table(simper.time.treat.hm, taxa_are_rows=T), physeq.simper.time.tax, sample_data(simper.time.sampdat))
colnames(tax_table(physeq.simper.time)) <- 
  c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", "OTU_Classification")
physeq.simper.time <- transform_sample_counts(physeq.simper.time, function(x){x*100})
sample_data(physeq.simper.time)$Treatment_Time <- ordered(sample_data(physeq.simper.time)$Treatment_Time, levels=c("LF_Pre", "LF_Post", "HF_Pre", "HF_Post", "SC_Pre", "SC_Post", "TV_Pre", "TV_Post"))

### HeatMap Time
# http://www.roymfrancis.com/a-guide-to-elegant-tiled-heatmaps-in-r/
# https://github.com/tidyverse/ggplot2/pull/2541
time.hm <- plot_heatmap(physeq.simper.time, sample.label = "Treatment_Time", sample.order = c("LF_Pre", "LF_Post", "HF_Pre", "HF_Post", "SC_Pre", "SC_Post", "TV_Pre", "TV_Post"), taxa.label = "OTU_Classification", taxa.order = "Phylum", low = "#FFFFCC", high = "firebrick3", na.value = "#FFFFFC") +
  geom_tile(colour="gray40") +
  geom_text(aes(label=sprintf("%0.2f", round(Abundance, digits=2)))) +
  scale_fill_gradient(name="Relative Abundance (%)", low = "#FFFFCC", high = "firebrick3", limits=c(0,12)) +
  scale_x_discrete(labels = c("Low Fat Pre", "Low Fat Post", "High Fat Pre", "High Fat Post",
                              "Saccharin Pre", "Saccharin Post", "Stevia Pre", "Stevia Post")) +
  scale_y_discrete(labels=c(expression(" "^a~"Bacteroides"), expression(" "^bcd~"S24-7"), 
                            expression(" "^bcd~"S24-7"), expression(" "^c~"S24-7"), 
                            expression(" "^c~"S24-7"), expression(" "^a~"Alistipes"),
                            expression(" "^bcd~"Ruminiclostridium"), expression(" "^bcd~"Lachnospiraceae"),
                            expression(" "^bd~"Lactococcus"), expression(" "^ab~"NK4A136"),
                            expression(" "^cd~"Anaeroplasma"))) +
  ylab("OTU Classification") + xlab("Group") +
  theme(panel.border=element_blank(),
        axis.text.x = element_text(angle=50, hjust=1.1, vjust=1.18, family="Arial", size=10, 
                                   margin = margin(t=0, r=0, b=0, l=0)),
        axis.text.y = element_text(family="Arial", size=10),
        axis.ticks.x=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_text(size=12, face="bold", family="Arial"),
        axis.title.y = element_text(margin = margin(t=0, r=20, b=0, l=0), size=12, face="bold", family="Arial"),
        axis.line=element_blank(),
        legend.title = element_text(family = "Arial", size=10, face="bold"),
        legend.text = element_text(family = "Arial", size=10),
        plot.title = element_text(family = "Arial", size=10, face="bold")
  ) +
  guides(fill = guide_colorbar(barheight = unit( 3 , "in" ),
                                ticks.color = "black",
                                ticks.linewidth = 1,
                                frame.color = "black",
                                frame.linewidth = 1))


```

### HeatMap Plot
```{r}
# https://cran.r-project.org/web/packages/cowplot/vignettes/plot_grid.html
#theme_set(theme_cowplot(font_family = "Arial"))
#save_plot("hm.tiff", plot_grid(post.hm, time.hm, labels= "AUTO", ncol = 1, align = 'v'), base_width = 7, #base_height = 10, dpi=600)


tiff("hm.tiff", width=180, height = 210, units="mm", res = 600)
grid.newpage()
pushViewport(viewport(layout=(grid.layout(4,1, widths=c(1,1,1,1), heights=c(0.04,1,0.04,1)))))
grid.text("A", x=unit(0.03, "npc"), vp=viewport(layout.pos.row=1, layout.pos.col=1), gp=gpar(fontsize=16,fontface="bold",fontfamily="Arial"))
print(time.hm, vp=viewport(layout.pos.row=2, layout.pos.col=1))
grid.text("B", x=unit(0.03, "npc"), vp=viewport(layout.pos.row=3, layout.pos.col=1), gp=gpar(fontsize=16,fontface="bold",fontfamily="Arial"))
print(post.hm, vp=viewport(layout.pos.row=4, layout.pos.col=1))
dev.off()




```



### SIMPER OTU No Sex
```{r}
# Pre-treatment
simper.pretty(data.frame(otu_table(physeq.pre)),
              data.frame(sample_data(physeq.pre)),
              c("Treatment", "Sex"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.pre')
stevia.pre.simper <- read.csv("stevia.pre_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.pre)),
               data.frame(sample_data(physeq.pre)),
               csv = stevia.pre.simper,
               c("Treatment", "Sex"),
               output_name = 'stevia.pre',
               taxonomy = data.frame(tax_table(physeq.pre)))
stevia.pre.simper.kw <- read.csv("stevia.pre_krusk_simper.csv")
for(i in 1:nrow(stevia.pre.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.pre))) == stevia.pre.simper.kw$OTU[i])
  stevia.pre.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.pre))[i,2], "-",
          data.frame(tax_table(physeq.pre))[i,3], "-",
          data.frame(tax_table(physeq.pre))[i,4], "-",
          data.frame(tax_table(physeq.pre))[i,5], "-",
          data.frame(tax_table(physeq.pre))[i,6])
}
write.table(stevia.pre.simper.kw, "stevia.pre_krusk_simper.csv", sep=",")

# Post-treatment
simper.pretty(data.frame(otu_table(physeq.post)),
              data.frame(sample_data(physeq.post)),
              c("Treatment"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.post')
stevia.post.simper <- read.csv("stevia.post_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.post)),
               data.frame(sample_data(physeq.post)),
               csv = stevia.post.simper,
               c("Treatment"),
               output_name = 'stevia.post',
               taxonomy = data.frame(tax_table(physeq.post)))
stevia.post.simper.kw <- read.csv("stevia.post_krusk_simper.csv")
for(i in 1:nrow(stevia.post.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.post))) == stevia.post.simper.kw$OTU[i])
  stevia.post.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.post))[i,2], "-",
          data.frame(tax_table(physeq.post))[i,3], "-",
          data.frame(tax_table(physeq.post))[i,4], "-",
          data.frame(tax_table(physeq.post))[i,5], "-",
          data.frame(tax_table(physeq.post))[i,6])
}
write.table(stevia.post.simper.kw, "stevia.post_krusk_simper.csv", sep=",")

# High Fat
simper.pretty(data.frame(otu_table(physeq.hf)),
              data.frame(sample_data(physeq.hf)),
              c("Time"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.hf')
stevia.hf.simper <- read.csv("stevia.hf_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.hf)),
               data.frame(sample_data(physeq.hf)),
               csv = stevia.hf.simper,
               c("Time"),
               output_name = 'stevia.hf',
               taxonomy = data.frame(tax_table(physeq.hf)))
stevia.hf.simper.kw <- read.csv("stevia.hf_krusk_simper.csv")
for(i in 1:nrow(stevia.hf.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.hf))) == stevia.hf.simper.kw$OTU[i])
  stevia.hf.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.hf))[i,2], "-",
          data.frame(tax_table(physeq.hf))[i,3], "-",
          data.frame(tax_table(physeq.hf))[i,4], "-",
          data.frame(tax_table(physeq.hf))[i,5], "-",
          data.frame(tax_table(physeq.hf))[i,6])
}
write.table(stevia.hf.simper.kw, "stevia.hf_krusk_simper.csv", sep=",")

# Low Fat
simper.pretty(data.frame(otu_table(physeq.lf)),
              data.frame(sample_data(physeq.lf)),
              c("Time"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.lf')
stevia.lf.simper <- read.csv("stevia.lf_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.lf)),
               data.frame(sample_data(physeq.lf)),
               csv = stevia.lf.simper,
               c("Time"),
               output_name = 'stevia.lf',
               taxonomy = data.frame(tax_table(physeq.lf)))
stevia.lf.simper.kw <- read.csv("stevia.lf_krusk_simper.csv")
for(i in 1:nrow(stevia.lf.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.lf))) == stevia.lf.simper.kw$OTU[i])
  stevia.lf.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.lf))[i,2], "-",
          data.frame(tax_table(physeq.lf))[i,3], "-",
          data.frame(tax_table(physeq.lf))[i,4], "-",
          data.frame(tax_table(physeq.lf))[i,5], "-",
          data.frame(tax_table(physeq.lf))[i,6])
}
write.table(stevia.lf.simper.kw, "stevia.lf_krusk_simper.csv", sep=",")

# Saccharin
simper.pretty(data.frame(otu_table(physeq.sc)),
              data.frame(sample_data(physeq.sc)),
              c("Time"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.sc')
stevia.sc.simper <- read.csv("stevia.sc_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.sc)),
               data.frame(sample_data(physeq.sc)),
               csv = stevia.sc.simper,
               c("Time"),
               output_name = 'stevia.sc',
               taxonomy = data.frame(tax_table(physeq.sc)))
stevia.sc.simper.kw <- read.csv("stevia.sc_krusk_simper.csv")
for(i in 1:nrow(stevia.sc.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.sc))) == stevia.sc.simper.kw$OTU[i])
  stevia.sc.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.sc))[i,2], "-",
          data.frame(tax_table(physeq.sc))[i,3], "-",
          data.frame(tax_table(physeq.sc))[i,4], "-",
          data.frame(tax_table(physeq.sc))[i,5], "-",
          data.frame(tax_table(physeq.sc))[i,6])
}
write.table(stevia.sc.simper.kw, "stevia.sc_krusk_simper.csv", sep=",")

# Stevia
simper.pretty(data.frame(otu_table(physeq.tv)),
              data.frame(sample_data(physeq.tv)),
              c("Time"),
              perc_cutoff=0.5, low_cutoff='y', low_val=0.01,
              output_name='stevia.tv')
stevia.tv.simper <- read.csv("stevia.tv_clean_simper.csv")
kruskal.pretty(data.frame(otu_table(physeq.tv)),
               data.frame(sample_data(physeq.tv)),
               csv = stevia.tv.simper,
               c("Time"),
               output_name = 'stevia.tv',
               taxonomy = data.frame(tax_table(physeq.tv)))
stevia.tv.simper.kw <- read.csv("stevia.tv_krusk_simper.csv")
for(i in 1:nrow(stevia.tv.simper.kw)){
  save <- which(rownames(data.frame(tax_table(physeq.tv))) == stevia.tv.simper.kw$OTU[i])
  stevia.tv.simper.kw$Taxonomy[i] <-
    paste(data.frame(tax_table(physeq.tv))[i,2], "-",
          data.frame(tax_table(physeq.tv))[i,3], "-",
          data.frame(tax_table(physeq.tv))[i,4], "-",
          data.frame(tax_table(physeq.tv))[i,5], "-",
          data.frame(tax_table(physeq.tv))[i,6])
}
write.table(stevia.tv.simper.kw, "stevia.tv_krusk_simper.csv", sep=",")






### BH CORRECTION FOR ALL OTU-LEVEL SIMPER COMPARISONS
stevia.pre.simper.kw$Group <- rep("Pre", nrow(stevia.pre.simper.kw))
stevia.pre.simper.kw$OTU <- as.character(stevia.pre.simper.kw$OTU)
stevia.pre.simper.kw$Comparison <- as.character(stevia.pre.simper.kw$Comparison)
stevia.pre.simper.kw$Taxonomy <- as.character(stevia.pre.simper.kw$Taxonomy)
stevia.post.simper.kw$Group <- rep("Post", nrow(stevia.post.simper.kw))
stevia.post.simper.kw$OTU <- as.character(stevia.post.simper.kw$OTU)
stevia.post.simper.kw$Comparison <- as.character(stevia.post.simper.kw$Comparison)
stevia.post.simper.kw$Taxonomy <- as.character(stevia.post.simper.kw$Taxonomy)
stevia.hf.simper.kw$Group <- rep("High Fat", nrow(stevia.hf.simper.kw))
stevia.hf.simper.kw$OTU <- as.character(stevia.hf.simper.kw$OTU)
stevia.hf.simper.kw$Comparison <- as.character(stevia.hf.simper.kw$Comparison)
stevia.hf.simper.kw$Taxonomy <- as.character(stevia.hf.simper.kw$Taxonomy)
stevia.lf.simper.kw$Group <- rep("Low Fat", nrow(stevia.lf.simper.kw))
stevia.lf.simper.kw$OTU <- as.character(stevia.lf.simper.kw$OTU)
stevia.lf.simper.kw$Comparison <- as.character(stevia.lf.simper.kw$Comparison)
stevia.lf.simper.kw$Taxonomy <- as.character(stevia.lf.simper.kw$Taxonomy)
stevia.sc.simper.kw$Group <- rep("Saccharin", nrow(stevia.sc.simper.kw))
stevia.sc.simper.kw$OTU <- as.character(stevia.sc.simper.kw$OTU)
stevia.sc.simper.kw$Comparison <- as.character(stevia.sc.simper.kw$Comparison)
stevia.sc.simper.kw$Taxonomy <- as.character(stevia.sc.simper.kw$Taxonomy)
stevia.sc.simper.kw$Group <- as.character(stevia.sc.simper.kw$Group)
stevia.tv.simper.kw$Group <- rep("Stevia", nrow(stevia.tv.simper.kw))
stevia.tv.simper.kw$OTU <- as.character(stevia.tv.simper.kw$OTU)
stevia.tv.simper.kw$Comparison <- as.character(stevia.tv.simper.kw$Comparison)
stevia.tv.simper.kw$Taxonomy <- as.character(stevia.tv.simper.kw$Taxonomy)
stevia.tv.simper.kw$Group <- as.character(stevia.tv.simper.kw$Group)
stevia.simper.all <- stevia.pre.simper.kw
stevia.simper.all[(nrow(stevia.simper.all)+1):(nrow(stevia.simper.all)+nrow(stevia.post.simper.kw)),] <- stevia.post.simper.kw
stevia.simper.all[(nrow(stevia.simper.all)+1):(nrow(stevia.simper.all)+nrow(stevia.hf.simper.kw)),] <- stevia.hf.simper.kw
stevia.simper.all[(nrow(stevia.simper.all)+1):(nrow(stevia.simper.all)+nrow(stevia.lf.simper.kw)),] <- stevia.lf.simper.kw
stevia.simper.all[(nrow(stevia.simper.all)+1):(nrow(stevia.simper.all)+nrow(stevia.sc.simper.kw)),] <- stevia.sc.simper.kw
stevia.simper.all[(nrow(stevia.simper.all)+1):(nrow(stevia.simper.all)+nrow(stevia.tv.simper.kw)),] <- stevia.tv.simper.kw
stevia.simper.all$fdr_krusk_p.val <- p.adjust(stevia.simper.all$krusk_p.val, "BH")
write.table(stevia.simper.all, "stevia.simper.nosex.csv", sep=",")
```







### Physiology
```{r}
### Summarize Data
phys.df <- data.frame(sample_data(physeq.pair))
phys.sum <- phys.df %>%
  group_by(Time, Treatment) %>%
  summarize(BW_Mean = mean(Body_Weight),
            BW_Median = median(Body_Weight),
            BW_SD = sd(Body_Weight),
            BW_SE = (sd(Body_Weight)/sqrt(length(Body_Weight))),
            BW_IQR = IQR(Body_Weight))
phys.post.df <- data.frame(sample_data(physeq.post))
phys.post.sum <- phys.post.df %>%
  group_by(Treatment) %>%
  summarize(BW_Mean = mean(Body_Weight),
            BW_Median = median(Body_Weight),
            BW_SD = sd(Body_Weight),
            BW_SE = (sd(Body_Weight)/sqrt(length(Body_Weight))),
            BW_IQR = IQR(Body_Weight),
            BG_Mean = mean(Blood_Glucose),
            BG_Median = median(Blood_Glucose),
            BG_SD = sd(Blood_Glucose),
            BG_SE = (sd(Blood_Glucose)/sqrt(length(Blood_Glucose))),
            BG_IQR = IQR(Blood_Glucose))

### Check Normality
# All, Body Weight
hist(phys.df$Body_Weight, breaks=10)
qqnorm(phys.df$Body_Weight)
qqline(phys.df$Body_Weight)
shapiro.test(phys.df$Body_Weight)
  # p-value = 4.363e-07
  # Not Normal
# Post, Body Weight
hist(phys.post.df$Body_Weight, breaks=10)
qqnorm(phys.post.df$Body_Weight)
qqline(phys.post.df$Body_Weight)
shapiro.test(phys.post.df$Body_Weight)
  # p-value = 0.00312
  # Not Normal
# Post, Blood Glucose
hist(phys.post.df$Blood_Glucose, breaks=10)
qqnorm(phys.post.df$Blood_Glucose)
qqline(phys.post.df$Blood_Glucose)
shapiro.test(phys.post.df$Blood_Glucose)
  # p-value = 0.0958
  # Normal


### Plot



### Test
# All, Time, Body Weight
wilcox.test(Body_Weight ~ Time, data=phys.df, paired=T)
  # p-value = 1.752e-07
# Post, Treatment, Body Weight
kruskal.test(formula = Body_Weight ~ Treatment, data=phys.post.df)
  # p-value = 0.0002352
kruskalmc(resp = Body_Weight ~ Treatment, data = phys.post.df)
  # Low Fat-High Fat
  # Low Fat-Saccharin
  # Low Fat-Stevia
pairwise.wilcox.test(phys.post.df$Body_Weight, phys.post.df$Treatment, p.adjust.method="fdr")
  # Low Fat-High Fat: p-value = 0.00045
  # Low Fat-Saccharin: p-value = 0.00013
  # Low Fat-Stevia: p-value = 0.00064
  # High Fat-Saccharin: p-value = 0.79977
  # High Fat-Stevia: p-value = 1.00000
  # Saccharin-Stevia: 0.79977
# Post, Treatment, Blood Glucose
summary(aov(Blood_Glucose ~ Treatment, data=phys.post.df))
  # p-value = 0.000262
TukeyHSD(aov(Blood_Glucose ~ Treatment, data=phys.post.df))
  # Low Fat-High Fat: p-value = 0.0004913
  # Low Fat-Saccharin: p-value = 0.0150677
  # Low Fat-Stevia: p-value = 0.0015190
  # High Fat-Saccharin: p-value = 0.6075598
  # High Fat-Stevia: p-value = 0.9939547
  # Saccharin-Stevia: p-value = 0.7810005


### Cross-Correlation
pairs(phys.post.df[,7:8])
  # Looks correlated
xyplot(Blood_Glucose ~ Body_Weight, phys.post.df)
summary(lm(Blood_Glucose ~ Body_Weight, phys.post.df))
  # p-value = 1.09e-10
  # R2 = 0.742
confint(lm(Blood_Glucose ~ Body_Weight, phys.post.df), level=0.95)

```



### miLineage
```{r}
### Load miLineage Results
load("miLineage/ml.all.bodyweight.RData")
  # ml.all.bw.results
  # No sig
load("miLineage/ml.all.bloodglucose.RData")
  # ml.all.bg.results
  # No sig
load("miLineage/ml.bodyweight.RData")
  # ml.bw.results
  # Sig
load("miLineage/ml.post.bodyweight.RData")
  # ml.post.bw.results
  # Sig
load("miLineage/ml.bloodglucose.RData")
  # ml.bg.results
  # Sig
load("miLineage/ml.post.both.bodyweight.RData")
  # ml.post.both.bw.results
  # No sig
load("miLineage/ml.post.both.bloodglucose.RData")
  # ml.post.both.bg.results
  # No sig
load("miLineage/ml.post.rem.bodyweight.RData")
  # ml.post.rem.bw.results
  # No sig
load("miLineage/ml.post.rem.bloodglucose.RData")
  # ml.post.rem.bg.results
  # No sig
load("miLineage/ml.post.rem.bodyweight.only.RData")
  # ml.post.rem.bw.only.results
  # No sig
load("miLineage/ml.post.rem.bloodglucose.only.RData")
  # ml.post.rem.bg.only.results
  # No sig

# Prep inputs
tax.ml <- as.matrix(tax_table(physeq.pair))
colnames(tax.ml) <- c("Rank1","Rank2","Rank3","Rank4","Rank5","Rank6","Rank7")
otu.ml <- data.frame(otu_table(physeq.pair))
otu.ml <- as.matrix(t(otu.ml))
var.bw.ml <- as.matrix(sample_data(physeq.pair)[,7])
  # Body_Weight


# Prep post inputs
tax2.ml <- as.matrix(tax_table(physeq.post))
colnames(tax2.ml) <- c("Rank1","Rank2","Rank3","Rank4","Rank5","Rank6","Rank7")
otu2.ml <- data.frame(otu_table(physeq.post))
otu2.ml <- as.matrix(t(otu2.ml))
var.ml <- as.matrix(sample_data(physeq.post)[,7:8])
var1.ml <- as.matrix(sample_data(physeq.post)[,7])
  # Body_Weight
var2.ml <- as.matrix(sample_data(physeq.post)[,8])
  # Blood_Glucose


# Prep post no Low Fat inputs
tax3.ml <- as.matrix(tax_table(physeq.post.rem))
colnames(tax3.ml) <- c("Rank1","Rank2","Rank3","Rank4","Rank5","Rank6","Rank7")
otu3.ml <- data.frame(otu_table(physeq.post.rem))
otu3.ml <- as.matrix(t(otu3.ml))
var.rem.ml <- as.matrix(sample_data(physeq.post.rem)[,7:8])
var.rem1.ml <- as.matrix(sample_data(physeq.post.rem)[,7])
  # Body_Weight
var.rem2.ml <- as.matrix(sample_data(physeq.post.rem)[,8])
  # Blood_Glucose

# Run test
ml.all.bw.results <- QCAT_GEE(OTU=otu2.ml, Tax=tax2.ml, X=var.ml, X.index = 1, Z=var.ml, Z.index=1,  fdr.alpha=0.05, n.resample = 100)
#save(ml.all.bw.results, file="ml.all.bodyweight.RData")

ml.all.bg.results <- QCAT_GEE(OTU=otu2.ml, Tax=tax2.ml, X=var.ml, X.index = 2, Z=var.ml, Z.index=2,  fdr.alpha=0.05, n.resample = 100)
#save(ml.all.bg.results, file="ml.all.bloodglucose.RData")

ml.bw.results <- QCAT_GEE(OTU=otu.ml, Tax=tax.ml, X=var.bw.ml, X.index = 1, Z=var.bw.ml, Z.index=1,  fdr.alpha=0.05, n.resample = 100)
#save(ml.bw.results, file = "ml.bodyweight.RData")

ml.bg.results <- QCAT_GEE(OTU=otu2.ml, Tax=tax2.ml, X=var2.ml, X.index = 1, Z=var2.ml, Z.index=1,  fdr.alpha=0.05, n.resample = 100)
#save(ml.bg.results, file = "ml.bloodglucose.RData")


### Post
ml.post.bw.results <- QCAT_GEE(OTU=otu2.ml, Tax=tax2.ml, X=var2.ml, X.index = 1, Z=var1.ml, Z.index=1,  fdr.alpha=0.05, n.resample = 100)
#save(ml.post.bw.results, file = "ml.post.bodyweight.RData")

ml.post.both.bw.results <- QCAT_GEE(OTU=otu2.ml, Tax=tax2.ml, X=var.ml, X.index = 1, Z=var.ml, Z.index=1,  fdr.alpha=0.05, n.resample = 100)
#save(ml.post.both.bw.results, file = "ml.post.both.bodyweight.RData")

ml.post.both.bg.results <- QCAT_GEE(OTU=otu2.ml, Tax=tax2.ml, X=var.ml, X.index = 2, Z=var.ml, Z.index=2,  fdr.alpha=0.05, n.resample = 100)
save(ml.post.both.bg.results, file = "ml.post.both.bloodglucose.RData")



### Post No Low Fat
ml.post.rem.bw.results <- QCAT_GEE(OTU=otu3.ml, Tax=tax3.ml, X=var.rem.ml, X.index = 1, Z=var.rem.ml, Z.index=1,  fdr.alpha=0.05, n.resample = 100)
#save(ml.post.rem.bw.results, file = "ml.post.rem.bodyweight.RData")

ml.post.rem.bg.results <- QCAT_GEE(OTU=otu3.ml, Tax=tax3.ml, X=var.rem.ml, X.index = 2, Z=var.rem.ml, Z.index=2,  fdr.alpha=0.05, n.resample = 100)
save(ml.post.rem.bg.results, file = "ml.post.rem.bloodglucose.RData")

ml.post.rem.bw.only.results <- QCAT_GEE(OTU=otu3.ml, Tax=tax3.ml, X=var.rem1.ml, X.index = 1, Z=var.rem1.ml, Z.index=1,  fdr.alpha=0.05, n.resample = 100)
save(ml.post.rem.bw.only.results, file = "ml.post.rem.bodyweight.only.RData")

ml.post.rem.bg.only.results <- QCAT_GEE(OTU=otu3.ml, Tax=tax3.ml, X=var.rem2.ml, X.index = 1, Z=var.rem2.ml, Z.index=1,  fdr.alpha=0.05, n.resample = 100)
save(ml.post.rem.bg.only.results, file = "ml.post.rem.bloodglucose.only.RData")

# Two-part test = Weighted
# Zero-part test = Unweighted
# Positive-part = Removes any lineages w/ 0 in any sample; looks at abundance
```










### Unused Bray-Curtis Code
```{r}

### All Female
bray.nmds.fem <- ordinate(physeq=physeq.fem, method="NMDS", distance="bray")
  # stress = 8.77398e-05

plot_ordination(physeq=physeq.fem, ordination=bray.nmds.fem, color="Treatment", shape="Time") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2")) +
  scale_shape_manual(values=c(19,2))



### All Male
bray.nmds.mal <- ordinate(physeq=physeq.mal, method="NMDS", distance="bray")
  # stress = 8.193224e-05 

plot_ordination(physeq=physeq.mal, ordination=bray.nmds.mal, color="Treatment", shape="Time") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2")) +
  scale_shape_manual(values=c(19,2))



### Pre Female
bray.nmds.pre.fem <- ordinate(physeq=physeq.pre.fem, method="NMDS", distance="bray")
  # stress = 0.1965918 

plot_ordination(physeq=physeq.pre.fem, ordination=bray.nmds.pre.fem, color="Treatment")

# Treatment Ellipses
sample_data(physeq.pre.fem)$Elip.treat <- paste(sample_data(physeq.pre.fem)$Treatment)
elip.nmds.pre.fem.treat <- data.frame(MDS1 = bray.nmds.pre.fem$points[,1], MDS2 = bray.nmds.pre.fem$points[,2],
                        Group = sample_data(physeq.pre.fem)$Elip.treat)
plot.new()
elip.ord.pre.fem.treat <- ordiellipse(bray.nmds.pre.fem, sample_data(physeq.pre.fem)$Elip.treat, display="sites", kind="se", conf=0.95, label=T)
elip.pre.fem.treat.df <- data.frame()
for(i in levels(elip.nmds.pre.fem.treat$Group)){
  elip.pre.fem.treat.df <- rbind(elip.pre.fem.treat.df, cbind(as.data.frame(with(elip.nmds.pre.fem.treat[elip.nmds.pre.fem.treat$Group==i,],
                                                     veganCovEllipse(elip.ord.pre.fem.treat[[i]]$cov,
                                                                     elip.ord.pre.fem.treat[[i]]$center,
                                                                     elip.ord.pre.fem.treat[[i]]$scale))),
                                  group=i))
}

# Plot w/ treatment ellip
plot_ordination(physeq=physeq.pre.fem, ordination=bray.nmds.pre.fem, color="Treatment") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2")) +
  geom_path(data=elip.pre.fem.treat.df, aes(x=NMDS1, y=NMDS2, colour=group), size=1, linetype=1)



### Pre Male
bray.nmds.pre.mal <- ordinate(physeq=physeq.pre.mal, method="NMDS", distance="bray")
  # stress = 0.1949269 
  # NO CONVERGENCE!!!

plot_ordination(physeq=physeq.pre.mal, ordination=bray.nmds.pre.mal, color="Treatment") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2"))

# Treatment Ellipses
sample_data(physeq.pre.mal)$Elip.treat <- paste(sample_data(physeq.pre.mal)$Treatment)
elip.nmds.pre.mal.treat <- data.frame(MDS1 = bray.nmds.pre.mal$points[,1], MDS2 = bray.nmds.pre.mal$points[,2],
                        Group = sample_data(physeq.pre.mal)$Elip.treat)
plot.new()
elip.ord.pre.mal.treat <- ordiellipse(bray.nmds.pre.mal, sample_data(physeq.pre.mal)$Elip.treat, display="sites", kind="se", conf=0.95, label=T)
elip.pre.mal.treat.df <- data.frame()
for(i in levels(elip.nmds.pre.mal.treat$Group)){
  elip.pre.mal.treat.df <- rbind(elip.pre.mal.treat.df, cbind(as.data.frame(with(elip.nmds.pre.mal.treat[elip.nmds.pre.mal.treat$Group==i,],
                                                     veganCovEllipse(elip.ord.pre.mal.treat[[i]]$cov,
                                                                     elip.ord.pre.mal.treat[[i]]$center,
                                                                     elip.ord.pre.mal.treat[[i]]$scale))),
                                  group=i))
}

# Plot w/ treatment ellip
plot_ordination(physeq=physeq.pre.mal, ordination=bray.nmds.pre.mal, color="Treatment") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2")) +
  geom_path(data=elip.pre.mal.treat.df, aes(x=NMDS1, y=NMDS2, colour=group), size=1, linetype=1)


### Post Female
bray.nmds.post.fem <- ordinate(physeq=physeq.post.fem, method="NMDS", distance="bray")
  # stress = 8.335943e-05

plot_ordination(physeq=physeq.post.fem, ordination=bray.nmds.post.fem, color="Treatment") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2"))

# Treatment Ellipses
sample_data(physeq.post.fem)$Elip.treat <- paste(sample_data(physeq.post.fem)$Treatment)
elip.nmds.post.fem.treat <- data.frame(MDS1 = bray.nmds.post.fem$points[,1], MDS2 = bray.nmds.post.fem$points[,2],
                        Group = sample_data(physeq.post.fem)$Elip.treat)
plot.new()
elip.ord.post.fem.treat <- ordiellipse(bray.nmds.post.fem, sample_data(physeq.post.fem)$Elip.treat, display="sites", kind="se", conf=0.95, label=T)
elip.post.fem.treat.df <- data.frame()
for(i in levels(elip.nmds.post.fem.treat$Group)){
  elip.post.fem.treat.df <- rbind(elip.post.fem.treat.df, cbind(as.data.frame(with(elip.nmds.post.fem.treat[elip.nmds.post.fem.treat$Group==i,],
                                                     veganCovEllipse(elip.ord.post.fem.treat[[i]]$cov,
                                                                     elip.ord.post.fem.treat[[i]]$center,
                                                                     elip.ord.post.fem.treat[[i]]$scale))),
                                  group=i))
}

# Plot w/ treatment ellip
plot_ordination(physeq=physeq.post.fem, ordination=bray.nmds.post.fem, color="Treatment") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2")) +
  geom_path(data=elip.post.fem.treat.df, aes(x=NMDS1, y=NMDS2, colour=group), size=1, linetype=1)


### Post Male
bray.nmds.post.mal <- ordinate(physeq=physeq.post.mal, method="NMDS", distance="bray")
  # stress = 8.658975e-05 

plot_ordination(physeq=physeq.post.mal, ordination=bray.nmds.post.mal, color="Treatment") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2"))

# Treatment Ellipses
sample_data(physeq.post.mal)$Elip.treat <- paste(sample_data(physeq.post.mal)$Treatment)
elip.nmds.post.mal.treat <- data.frame(MDS1 = bray.nmds.post.mal$points[,1], MDS2 = bray.nmds.post.mal$points[,2],
                        Group = sample_data(physeq.post.mal)$Elip.treat)
plot.new()
elip.ord.post.mal.treat <- ordiellipse(bray.nmds.post.mal, sample_data(physeq.post.mal)$Elip.treat, display="sites", kind="se", conf=0.95, label=T)
elip.post.mal.treat.df <- data.frame()
for(i in levels(elip.nmds.post.mal.treat$Group)){
  elip.post.mal.treat.df <- rbind(elip.post.mal.treat.df, cbind(as.data.frame(with(elip.nmds.post.mal.treat[elip.nmds.post.mal.treat$Group==i,],
                                                     veganCovEllipse(elip.ord.post.mal.treat[[i]]$cov,
                                                                     elip.ord.post.mal.treat[[i]]$center,
                                                                     elip.ord.post.mal.treat[[i]]$scale))),
                                  group=i))
}

# Plot w/ treatment ellip
plot_ordination(physeq=physeq.post.mal, ordination=bray.nmds.post.mal, color="Treatment") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2")) +
  geom_path(data=elip.post.mal.treat.df, aes(x=NMDS1, y=NMDS2, colour=group), size=1, linetype=1)



### Post Female w/o Low Fat
bray.nmds.post.fem.rem <- ordinate(physeq=physeq.post.fem.rem, method="NMDS", distance="bray")
  # stress = 0.169206 

plot_ordination(physeq=physeq.post.fem.rem, ordination=bray.nmds.post.fem.rem, color="Treatment") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2")) +

# Treatment Ellipses
sample_data(physeq.post.fem.rem)$Elip.treat <- paste(sample_data(physeq.post.fem.rem)$Treatment)
elip.nmds.post.fem.rem.treat <- data.frame(MDS1 = bray.nmds.post.fem.rem$points[,1], MDS2 = bray.nmds.post.fem.rem$points[,2],
                        Group = sample_data(physeq.post.fem.rem)$Elip.treat)
plot.new()
elip.ord.post.fem.rem.treat <- ordiellipse(bray.nmds.post.fem.rem, sample_data(physeq.post.fem.rem)$Elip.treat, display="sites", kind="se", conf=0.95, label=T)
elip.post.fem.rem.treat.df <- data.frame()
for(i in levels(elip.nmds.post.fem.rem.treat$Group)){
  elip.post.fem.rem.treat.df <- rbind(elip.post.fem.rem.treat.df, cbind(as.data.frame(with(elip.nmds.post.fem.rem.treat[elip.nmds.post.fem.rem.treat$Group==i,],
                                                     veganCovEllipse(elip.ord.post.fem.rem.treat[[i]]$cov,
                                                                     elip.ord.post.fem.rem.treat[[i]]$center,
                                                                     elip.ord.post.fem.rem.treat[[i]]$scale))),
                                  group=i))
}

# Plot w/ treatment ellip
plot_ordination(physeq=physeq.post.fem.rem, ordination=bray.nmds.post.fem.rem, color="Treatment") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2")) +
  geom_path(data=elip.post.fem.rem.treat.df, aes(x=NMDS1, y=NMDS2, colour=group), size=1, linetype=1)



### Post Male w/o Low Fat
bray.nmds.post.mal.rem <- ordinate(physeq=physeq.post.mal.rem, method="NMDS", distance="bray")
  # stress = 0.160679

plot_ordination(physeq=physeq.post.mal.rem, ordination=bray.nmds.post.mal.rem, color="Treatment") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2"))

# Treatment Ellipses
sample_data(physeq.post.mal.rem)$Elip.treat <- paste(sample_data(physeq.post.mal.rem)$Treatment)
elip.nmds.post.mal.rem.treat <- data.frame(MDS1 = bray.nmds.post.mal.rem$points[,1], MDS2 = bray.nmds.post.mal.rem$points[,2],
                        Group = sample_data(physeq.post.mal.rem)$Elip.treat)
plot.new()
elip.ord.post.mal.rem.treat <- ordiellipse(bray.nmds.post.mal.rem, sample_data(physeq.post.mal.rem)$Elip.treat, display="sites", kind="se", conf=0.95, label=T)
elip.post.mal.rem.treat.df <- data.frame()
for(i in levels(elip.nmds.post.mal.rem.treat$Group)){
  elip.post.mal.rem.treat.df <- rbind(elip.post.mal.rem.treat.df, cbind(as.data.frame(with(elip.nmds.post.mal.rem.treat[elip.nmds.post.mal.rem.treat$Group==i,],
                                                     veganCovEllipse(elip.ord.post.mal.rem.treat[[i]]$cov,
                                                                     elip.ord.post.mal.rem.treat[[i]]$center,
                                                                     elip.ord.post.mal.rem.treat[[i]]$scale))),
                                  group=i))
}

# Plot w/ treatment ellip
plot_ordination(physeq=physeq.post.mal.rem, ordination=bray.nmds.post.mal.rem, color="Treatment") +
  scale_color_manual(values=c("brown2", "rosybrown", "limegreen", "dodgerblue2")) +
  geom_path(data=elip.post.mal.rem.treat.df, aes(x=NMDS1, y=NMDS2, colour=group), size=1, linetype=1)
```

